export const SEED_ENTITIES = [
    // 1. Tornado Cash (Mixer - OFAC Sanctioned)
    {
        id: "ent-tornado-cash",
        name: "Tornado Cash",
        type: "MIXER",
        category: "Non-Custodial Privacy Protocol",
        description: "OFAC-sanctioned smart contract mixer on Ethereum utilizing zk-SNARKs to break transaction linkability.",
        confidence: "VERIFIED",
        source: "US Treasury OFAC Specially Designated Nationals (SDN) List",
        lastVerified: new Date("2026-06-01"),
        website: "https://tornado.cash",
        isKycCompliant: false,
        baseRiskScore: 95,
        addresses: [
            {
                address: "0xd90e2f925da726b50c4ed8d0fb90ad053324f31b",
                chain: "ethereum",
                label: "Tornado.Cash: 100 ETH Pool",
                confidence: "VERIFIED",
                source: "OFAC SDN List / Etherscan Verified",
                lastVerified: new Date("2026-06-01"),
            },
            {
                address: "0x47ce0c6ed5b0ce3d3a51fdb1c52dc66a7c3c2936",
                chain: "ethereum",
                label: "Tornado.Cash: 10 ETH Pool",
                confidence: "VERIFIED",
                source: "OFAC SDN List",
                lastVerified: new Date("2026-06-01"),
            },
            {
                address: "0x12d66f87a04a9e220743712ce6d9bb1b5616b8fc",
                chain: "ethereum",
                label: "Tornado.Cash: 0.1 ETH Pool",
                confidence: "VERIFIED",
                source: "OFAC SDN List",
                lastVerified: new Date("2026-06-01"),
            },
        ],
    },
    // 2. Synapse Bridge (Bridge)
    {
        id: "ent-synapse-bridge",
        name: "Synapse Bridge",
        type: "BRIDGE",
        category: "Cross-Chain Liquidity Router",
        description: "Decentralized cross-chain communication network facilitating asset transfers across EVM and non-EVM chains.",
        confidence: "VERIFIED",
        source: "Official Protocol Contracts / DefiLlama",
        lastVerified: new Date("2026-07-15"),
        website: "https://synapseprotocol.com",
        isKycCompliant: false,
        baseRiskScore: 40,
        addresses: [
            {
                address: "0x2796317b0ff8538f253012862c06787adfb8ceb6",
                chain: "ethereum",
                label: "Synapse: Bridge Router",
                confidence: "VERIFIED",
                source: "Synapse Protocol Verified",
                lastVerified: new Date("2026-07-15"),
            },
        ],
    },
    // 3. Binance (Exchange - KYC Compliant)
    {
        id: "ent-binance",
        name: "Binance",
        type: "EXCHANGE",
        category: "Centralized Exchange",
        description: "Centralized cryptocurrency exchange with KYC/AML compliance programs and subpoena response unit.",
        confidence: "VERIFIED",
        source: "Exchange Public Hot Wallets / Blockchain Intelligence",
        lastVerified: new Date("2026-08-01"),
        website: "https://binance.com",
        jurisdiction: "Global / Cayman / Multiple",
        isKycCompliant: true,
        baseRiskScore: 10,
        addresses: [
            {
                address: "0x28c6c06298d514db089934071355e5743bf21d60",
                chain: "ethereum",
                label: "Binance: Hot Wallet 14",
                confidence: "VERIFIED",
                source: "Etherscan Label Cloud",
                lastVerified: new Date("2026-08-01"),
            },
            {
                address: "0xdfd5293d8e347dfee59e53b2433fe05ba07a8291",
                chain: "ethereum",
                label: "Binance: Hot Wallet 15",
                confidence: "VERIFIED",
                source: "Etherscan Label Cloud",
                lastVerified: new Date("2026-08-01"),
            },
            {
                address: "1NDyJtNTjmwk5xPNhjgAMu4HDHigtobu1s",
                chain: "bitcoin",
                label: "Binance Cold Storage",
                confidence: "VERIFIED",
                source: "Chainalysis Intelligence Feed",
                lastVerified: new Date("2026-08-01"),
            },
        ],
    },
    // 4. Coinbase (Exchange - US Regulated)
    {
        id: "ent-coinbase",
        name: "Coinbase",
        type: "EXCHANGE",
        category: "US Regulated Centralized Exchange",
        description: "US-regulated cryptocurrency exchange subject to FinCEN MSB regulations and BSA compliance.",
        confidence: "VERIFIED",
        source: "SEC Filings / Public Hot Wallets",
        lastVerified: new Date("2026-08-01"),
        website: "https://coinbase.com",
        jurisdiction: "United States",
        isKycCompliant: true,
        baseRiskScore: 5,
        addresses: [
            {
                address: "0x503828976d22510aad0201ac7ec8829322757974",
                chain: "ethereum",
                label: "Coinbase: Hot Wallet 2",
                confidence: "VERIFIED",
                source: "Public Registry",
                lastVerified: new Date("2026-08-01"),
            },
            {
                address: "0x71660c4005ba85c37ccec55d0c4493e66fe775d3",
                chain: "ethereum",
                label: "Coinbase: Hot Wallet 3",
                confidence: "VERIFIED",
                source: "Public Registry",
                lastVerified: new Date("2026-08-01"),
            },
        ],
    },
    // 5. Kraken (Exchange)
    {
        id: "ent-kraken",
        name: "Kraken",
        type: "EXCHANGE",
        category: "Centralized Exchange",
        description: "US-headquartered exchange with compliance and law enforcement subpoena processing.",
        confidence: "VERIFIED",
        source: "Verified Exchange Registry",
        lastVerified: new Date("2026-08-01"),
        website: "https://kraken.com",
        jurisdiction: "United States",
        isKycCompliant: true,
        baseRiskScore: 8,
        addresses: [
            {
                address: "bc1qkraken00000000000000000000000000000000",
                chain: "bitcoin",
                label: "Kraken: Deposit Cluster",
                confidence: "HIGH",
                source: "Investigative Clustering",
                lastVerified: new Date("2026-08-01"),
            },
            {
                address: "0x267be1c1d684f78cb4f6a176c4911b741e4ffdc0",
                chain: "ethereum",
                label: "Kraken: Hot Wallet 4",
                confidence: "VERIFIED",
                source: "Etherscan Verified",
                lastVerified: new Date("2026-08-01"),
            },
        ],
    },
    // 6. Hydra Market / Darknet Narcotics Vendor (Illicit / Marketplace)
    {
        id: "ent-darknet-narcotics",
        name: "Hydra / Silk Narcotics Syndicate",
        type: "KNOWN_ILLICIT",
        category: "Darknet Narcotics Distribution",
        description: "High-confidence drug enforcement target cluster associated with synthetic opioid distribution and illicit chemical purchases.",
        confidence: "HIGH",
        source: "DEA / Federal Law Enforcement Task Force Bulletins",
        lastVerified: new Date("2026-08-10"),
        isKycCompliant: false,
        baseRiskScore: 98,
        addresses: [
            {
                address: "0x98174f85e49f87f4c9c1b3f9429188d3f6a2b001",
                chain: "ethereum",
                label: "Flagged Vendor Wallet 001",
                confidence: "HIGH",
                source: "Narcotics Tracing Evidence",
                lastVerified: new Date("2026-08-10"),
            },
            {
                address: "bc1q9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3b2c1d",
                chain: "bitcoin",
                label: "Syndicate Primary Vault",
                confidence: "HIGH",
                source: "Task Force Intelligence",
                lastVerified: new Date("2026-08-10"),
            },
        ],
    },
    // 6b. Lazarus Group / North Korea State Cybercrime (OFAC Sanctioned)
    {
        id: "ent-lazarus-group",
        name: "Lazarus Group (DPRK State Cybercrime)",
        type: "KNOWN_ILLICIT",
        category: "State-Sponsored Cybercrime / OFAC SDN List",
        description: "OFAC-sanctioned North Korean state-sponsored cyber illicit group responsible for the $625M Ronin Network exploit and major ransomware/bridge hacks.",
        confidence: "VERIFIED",
        source: "US Treasury OFAC Specially Designated Nationals (SDN) List / FBI Cyber Advisory",
        lastVerified: new Date("2026-08-15"),
        isKycCompliant: false,
        baseRiskScore: 100,
        addresses: [
            {
                address: "0x098b716b8aaf21512996dc57eb0615e2383e2f96",
                chain: "ethereum",
                label: "Lazarus Group: Ronin Bridge Exploiter Main",
                confidence: "VERIFIED",
                source: "OFAC SDN List / FBI Cyber Bulletin",
                lastVerified: new Date("2026-08-15"),
            },
            {
                address: "0xa7e5d5a720f06526557c512402ddc6d772c6f03c",
                chain: "ethereum",
                label: "Lazarus Group: Associated Stolen Funds Vault",
                confidence: "VERIFIED",
                source: "OFAC SDN List",
                lastVerified: new Date("2026-08-15"),
            },
            {
                address: "0x15ec451a44c9b32ac16e1728b8a1056980b90fd5",
                chain: "ethereum",
                label: "Lazarus Group: Horizon Bridge Hack Vault",
                confidence: "VERIFIED",
                source: "OFAC SDN List",
                lastVerified: new Date("2026-08-15"),
            },
        ],
    },
    // 7. Popular Token & Protocol Smart Contracts
    {
        id: "ent-weth-protocol",
        name: "Wrapped Ether (WETH)",
        type: "SERVICE",
        category: "Token Wrapper Protocol",
        description: "Standard WETH token contract wrapping native ETH into ERC-20 compliant tokens.",
        confidence: "VERIFIED",
        source: "Etherscan Verified Contract",
        lastVerified: new Date("2026-08-15"),
        isKycCompliant: false,
        baseRiskScore: 5,
        addresses: [
            {
                address: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
                chain: "ethereum",
                label: "WETH Smart Contract",
                confidence: "VERIFIED",
                source: "Canonical WETH Contract",
                lastVerified: new Date("2026-08-15"),
            },
        ],
    },
    {
        id: "ent-dai-stablecoin",
        name: "DAI Stablecoin (MakerDAO)",
        type: "SERVICE",
        category: "Decentralized Stablecoin Protocol",
        description: "Decentralized algorithmic stablecoin contract managed by MakerDAO.",
        confidence: "VERIFIED",
        source: "Etherscan Verified Contract",
        lastVerified: new Date("2026-08-15"),
        isKycCompliant: false,
        baseRiskScore: 5,
        addresses: [
            {
                address: "0x6b175474e89094c44da98b954eedeac495271d0f",
                chain: "ethereum",
                label: "DAI Token Contract",
                confidence: "VERIFIED",
                source: "MakerDAO Canonical DAI Contract",
                lastVerified: new Date("2026-08-15"),
            },
        ],
    },
    {
        id: "ent-mkr-governance",
        name: "Maker (MKR) Governance",
        type: "SERVICE",
        category: "DeFi Governance Protocol",
        description: "Governance token smart contract for MakerDAO ecosystem.",
        confidence: "VERIFIED",
        source: "Etherscan Verified Contract",
        lastVerified: new Date("2026-08-15"),
        isKycCompliant: false,
        baseRiskScore: 5,
        addresses: [
            {
                address: "0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2",
                chain: "ethereum",
                label: "MKR Governance Contract",
                confidence: "VERIFIED",
                source: "MakerDAO Canonical MKR Contract",
                lastVerified: new Date("2026-08-15"),
            },
        ],
    },
    {
        id: "ent-snx-protocol",
        name: "Synthetix (SNX)",
        type: "SERVICE",
        category: "DeFi Derivatives Protocol",
        description: "Synthetix Network token contract facilitating synthetic asset trading.",
        confidence: "VERIFIED",
        source: "Etherscan Verified Contract",
        lastVerified: new Date("2026-08-15"),
        isKycCompliant: false,
        baseRiskScore: 5,
        addresses: [
            {
                address: "0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f",
                chain: "ethereum",
                label: "SNX Token Contract",
                confidence: "VERIFIED",
                source: "Synthetix Canonical SNX Contract",
                lastVerified: new Date("2026-08-15"),
            },
        ],
    },
    {
        id: "ent-usdc-stablecoin",
        name: "USD Coin (USDC)",
        type: "SERVICE",
        category: "Fiat-Backed Stablecoin Protocol",
        description: "Centre consortium fiat-backed stablecoin smart contract.",
        confidence: "VERIFIED",
        source: "Etherscan Verified Contract",
        lastVerified: new Date("2026-08-15"),
        isKycCompliant: true,
        baseRiskScore: 5,
        addresses: [
            {
                address: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
                chain: "ethereum",
                label: "USDC Smart Contract",
                confidence: "VERIFIED",
                source: "Centre Consortium Canonical USDC",
                lastVerified: new Date("2026-08-15"),
            },
        ],
    },
    {
        id: "ent-usdt-stablecoin",
        name: "Tether (USDT)",
        type: "SERVICE",
        category: "Fiat-Backed Stablecoin Protocol",
        description: "Tether USD ERC-20 smart contract on Ethereum.",
        confidence: "VERIFIED",
        source: "Etherscan Verified Contract",
        lastVerified: new Date("2026-08-15"),
        isKycCompliant: true,
        baseRiskScore: 5,
        addresses: [
            {
                address: "0xdac17f958d2ee523a2206206994597c13d831ec7",
                chain: "ethereum",
                label: "Tether USDT Contract",
                confidence: "VERIFIED",
                source: "Tether Limited Canonical USDT",
                lastVerified: new Date("2026-08-15"),
            },
        ],
    },
    // 8. Uniswap V3 (DEX / DeFi Protocol)
    {
        id: "ent-uniswap-v3",
        name: "Uniswap V3 Protocol",
        type: "SERVICE",
        category: "Decentralized Exchange (DEX)",
        description: "Automated market maker liquidity protocol for decentralised asset exchange.",
        confidence: "VERIFIED",
        source: "Uniswap Verified Contracts",
        lastVerified: new Date("2026-08-01"),
        website: "https://uniswap.org",
        isKycCompliant: false,
        baseRiskScore: 0,
        addresses: [
            {
                address: "0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45",
                chain: "ethereum",
                label: "Uniswap V3: SwapRouter02",
                confidence: "VERIFIED",
                source: "Uniswap Verified Contracts",
                lastVerified: new Date("2026-08-01"),
            },
            {
                address: "0xe592427a0aece92de3edee1f18e0157c05861564",
                chain: "ethereum",
                label: "Uniswap V3: Router",
                confidence: "VERIFIED",
                source: "Uniswap Verified Contracts",
                lastVerified: new Date("2026-08-01"),
            },
        ],
    },
    // 9. Hop Protocol (Bridge)
    {
        id: "ent-hop-protocol",
        name: "Hop Protocol",
        type: "BRIDGE",
        category: "Cross-Chain Bridge",
        description: "Scalable rollup-to-rollup cross-chain bridge protocol.",
        confidence: "VERIFIED",
        source: "Hop Protocol Verified Contracts",
        lastVerified: new Date("2026-08-01"),
        website: "https://hop.exchange",
        isKycCompliant: false,
        baseRiskScore: 35,
        addresses: [
            {
                address: "0x3644049261326574f07a4a2f89d3807d9d7b93a0",
                chain: "ethereum",
                label: "Hop Protocol: ETH Bridge",
                confidence: "VERIFIED",
                source: "Hop Registry",
                lastVerified: new Date("2026-08-01"),
            },
        ],
    },
    // 10. Wasabi / CoinJoin Pool (Mixer - Privacy)
    {
        id: "ent-wasabi-coinjoin",
        name: "Wasabi CoinJoin Pool",
        type: "MIXER",
        category: "Bitcoin Privacy Protocol",
        description: "Bitcoin Chaumian CoinJoin privacy coordinator breaking UTXO lineage.",
        confidence: "HIGH",
        source: "Bitcoin Intelligence Heuristics",
        lastVerified: new Date("2026-08-01"),
        website: "https://wasabiwallet.io",
        isKycCompliant: false,
        baseRiskScore: 85,
        addresses: [
            {
                address: "bc1qwasabicoinjoin000000000000000000000000",
                chain: "bitcoin",
                label: "Wasabi Coordinator Pool",
                confidence: "HIGH",
                source: "CIOH Heuristic Engine",
                lastVerified: new Date("2026-08-01"),
            },
        ],
    },
    // 11. OKX (Exchange)
    {
        id: "ent-okx",
        name: "OKX Exchange",
        type: "EXCHANGE",
        category: "Centralized Exchange",
        description: "Global centralized cryptocurrency exchange with mandatory KYC compliance.",
        confidence: "VERIFIED",
        source: "Etherscan Label Cloud",
        lastVerified: new Date("2026-08-01"),
        website: "https://okx.com",
        isKycCompliant: true,
        baseRiskScore: 10,
        addresses: [
            {
                address: "0x6cc5f688a315f3dc28a7781717a9a798a59fda7b",
                chain: "ethereum",
                label: "OKX: Deposit Router",
                confidence: "VERIFIED",
                source: "Etherscan Label Cloud",
                lastVerified: new Date("2026-08-01"),
            },
        ],
    },
];
//# sourceMappingURL=seed-data.js.map