import { Entity } from "@crypto-tracer/types";

export const SEED_ENTITIES: Entity[] = [
  // 1. Tornado Cash (Mixer - OFAC Sanctioned)
  {
    id: "ent-tornado-cash",
    name: "Tornado Cash",
    type: "MIXER",
    category: "Non-Custodial Privacy Protocol",
    description: "OFAC-sanctioned smart contract mixer on Ethereum utilizing zk-SNARKs to break transaction linkability.",
    confidence: "VERIFIED",
    source: "US Treasury OFAC Specially Designated Nationals (SDN) List",
    lastVerified: new Date("2026-06-01"),
    website: "https://tornado.cash",
    isKycCompliant: false,
    baseRiskScore: 95,
    addresses: [
      {
        address: "0xd90e2f925da726b50c4ed8d0fb90ad053324f31b",
        chain: "ethereum",
        label: "Tornado.Cash: 100 ETH Pool",
        confidence: "VERIFIED",
        source: "OFAC SDN List / Etherscan Verified",
        lastVerified: new Date("2026-06-01"),
      },
      {
        address: "0x47ce0c6ed5b0ce3d3a51fdb1c52dc66a7c3c2936",
        chain: "ethereum",
        label: "Tornado.Cash: 10 ETH Pool",
        confidence: "VERIFIED",
        source: "OFAC SDN List",
        lastVerified: new Date("2026-06-01"),
      },
      {
        address: "0x12d66f87a04a9e220743712ce6d9bb1b5616b8fc",
        chain: "ethereum",
        label: "Tornado.Cash: 0.1 ETH Pool",
        confidence: "VERIFIED",
        source: "OFAC SDN List",
        lastVerified: new Date("2026-06-01"),
      },
    ],
  },
  // 2. Synapse Bridge (Bridge)
  {
    id: "ent-synapse-bridge",
    name: "Synapse Bridge",
    type: "BRIDGE",
    category: "Cross-Chain Liquidity Router",
    description: "Decentralized cross-chain communication network facilitating asset transfers across EVM and non-EVM chains.",
    confidence: "VERIFIED",
    source: "Official Protocol Contracts / DefiLlama",
    lastVerified: new Date("2026-07-15"),
    website: "https://synapseprotocol.com",
    isKycCompliant: false,
    baseRiskScore: 40,
    addresses: [
      {
        address: "0x2796317b0ff8538f253012862c06787adfb8ceb6",
        chain: "ethereum",
        label: "Synapse: Bridge Router",
        confidence: "VERIFIED",
        source: "Synapse Protocol Verified",
        lastVerified: new Date("2026-07-15"),
      },
    ],
  },
  // 3. Binance (Exchange - KYC Compliant)
  {
    id: "ent-binance",
    name: "Binance",
    type: "EXCHANGE",
    category: "Centralized Exchange",
    description: "Centralized cryptocurrency exchange with KYC/AML compliance programs and subpoena response unit.",
    confidence: "VERIFIED",
    source: "Exchange Public Hot Wallets / Blockchain Intelligence",
    lastVerified: new Date("2026-08-01"),
    website: "https://binance.com",
    jurisdiction: "Global / Cayman / Multiple",
    isKycCompliant: true,
    baseRiskScore: 10,
    addresses: [
      {
        address: "0x28c6c06298d514db089934071355e5743bf21d60",
        chain: "ethereum",
        label: "Binance: Hot Wallet 14",
        confidence: "VERIFIED",
        source: "Etherscan Label Cloud",
        lastVerified: new Date("2026-08-01"),
      },
      {
        address: "0xdfd5293d8e347dfee59e53b2433fe05ba07a8291",
        chain: "ethereum",
        label: "Binance: Hot Wallet 15",
        confidence: "VERIFIED",
        source: "Etherscan Label Cloud",
        lastVerified: new Date("2026-08-01"),
      },
      {
        address: "1NDyJtNTjmwk5xPNhjgAMu4HDHigtobu1s",
        chain: "bitcoin",
        label: "Binance Cold Storage",
        confidence: "VERIFIED",
        source: "Chainalysis Intelligence Feed",
        lastVerified: new Date("2026-08-01"),
      },
    ],
  },
  // 4. Coinbase (Exchange - US Regulated)
  {
    id: "ent-coinbase",
    name: "Coinbase",
    type: "EXCHANGE",
    category: "US Regulated Centralized Exchange",
    description: "US-regulated cryptocurrency exchange subject to FinCEN MSB regulations and BSA compliance.",
    confidence: "VERIFIED",
    source: "SEC Filings / Public Hot Wallets",
    lastVerified: new Date("2026-08-01"),
    website: "https://coinbase.com",
    jurisdiction: "United States",
    isKycCompliant: true,
    baseRiskScore: 5,
    addresses: [
      {
        address: "0x503828976d22510aad0201ac7ec8829322757974",
        chain: "ethereum",
        label: "Coinbase: Hot Wallet 2",
        confidence: "VERIFIED",
        source: "Public Registry",
        lastVerified: new Date("2026-08-01"),
      },
      {
        address: "0x71660c4005ba85c37ccec55d0c4493e66fe775d3",
        chain: "ethereum",
        label: "Coinbase: Hot Wallet 3",
        confidence: "VERIFIED",
        source: "Public Registry",
        lastVerified: new Date("2026-08-01"),
      },
    ],
  },
  // 5. Kraken (Exchange)
  {
    id: "ent-kraken",
    name: "Kraken",
    type: "EXCHANGE",
    category: "Centralized Exchange",
    description: "US-headquartered exchange with compliance and law enforcement subpoena processing.",
    confidence: "VERIFIED",
    source: "Verified Exchange Registry",
    lastVerified: new Date("2026-08-01"),
    website: "https://kraken.com",
    jurisdiction: "United States",
    isKycCompliant: true,
    baseRiskScore: 8,
    addresses: [
      {
        address: "bc1qkraken00000000000000000000000000000000",
        chain: "bitcoin",
        label: "Kraken: Deposit Cluster",
        confidence: "HIGH",
        source: "Investigative Clustering",
        lastVerified: new Date("2026-08-01"),
      },
      {
        address: "0x267be1c1d684f78cb4f6a176c4911b741e4ffdc0",
        chain: "ethereum",
        label: "Kraken: Hot Wallet 4",
        confidence: "VERIFIED",
        source: "Etherscan Verified",
        lastVerified: new Date("2026-08-01"),
      },
    ],
  },
  // 6. Hydra Market / Darknet Narcotics Vendor (Illicit / Marketplace)
  {
    id: "ent-darknet-narcotics",
    name: "Hydra / Silk Narcotics Syndicate",
    type: "KNOWN_ILLICIT",
    category: "Darknet Narcotics Distribution",
    description: "High-confidence drug enforcement target cluster associated with synthetic opioid distribution and illicit chemical purchases.",
    confidence: "HIGH",
    source: "DEA / Federal Law Enforcement Task Force Bulletins",
    lastVerified: new Date("2026-08-10"),
    isKycCompliant: false,
    baseRiskScore: 98,
    addresses: [
      {
        address: "0x98174f85e49f87f4c9c1b3f9429188d3f6a2b001",
        chain: "ethereum",
        label: "Flagged Vendor Wallet 001",
        confidence: "HIGH",
        source: "Narcotics Tracing Evidence",
        lastVerified: new Date("2026-08-10"),
      },
      {
        address: "bc1q9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3b2c1d",
        chain: "bitcoin",
        label: "Syndicate Primary Vault",
        confidence: "HIGH",
        source: "Task Force Intelligence",
        lastVerified: new Date("2026-08-10"),
      },
    ],
  },
  // 7. Uniswap V3 (DEX / Protocol - Neutral Risk)
  {
    id: "ent-uniswap-v3",
    name: "Uniswap V3 Protocol",
    type: "SERVICE",
    category: "Decentralized Exchange (DEX)",
    description: "Automated market maker protocol on Ethereum for decentralized token swapping. Neutral DeFi protocol.",
    confidence: "VERIFIED",
    source: "Uniswap Official Deployment Registry / Etherscan",
    lastVerified: new Date("2026-08-01"),
    website: "https://uniswap.org",
    isKycCompliant: false,
    baseRiskScore: 0,
    addresses: [
      {
        address: "0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45",
        chain: "ethereum",
        label: "Uniswap V3: SwapRouter02",
        confidence: "VERIFIED",
        source: "Uniswap Verified Contracts",
        lastVerified: new Date("2026-08-01"),
      },
      {
        address: "0xe592427a0aece92de3edee1f18e0157c05861564",
        chain: "ethereum",
        label: "Uniswap V3: Router",
        confidence: "VERIFIED",
        source: "Uniswap Verified Contracts",
        lastVerified: new Date("2026-08-01"),
      },
    ],
  },
  // 8. Hop Protocol (Bridge)
  {
    id: "ent-hop-protocol",
    name: "Hop Protocol",
    type: "BRIDGE",
    category: "Cross-Chain Bridge",
    description: "Scalable rollup-to-rollup cross-chain bridge protocol.",
    confidence: "VERIFIED",
    source: "Hop Protocol Verified Contracts",
    lastVerified: new Date("2026-08-01"),
    website: "https://hop.exchange",
    isKycCompliant: false,
    baseRiskScore: 35,
    addresses: [
      {
        address: "0x3644049261326574f07a4a2f89d3807d9d7b93a0",
        chain: "ethereum",
        label: "Hop Protocol: ETH Bridge",
        confidence: "VERIFIED",
        source: "Hop Registry",
        lastVerified: new Date("2026-08-01"),
      },
    ],
  },
  // 9. Wasabi / CoinJoin Pool (Mixer - Privacy)
  {
    id: "ent-wasabi-coinjoin",
    name: "Wasabi CoinJoin Pool",
    type: "MIXER",
    category: "Bitcoin Privacy Protocol",
    description: "Bitcoin Chaumian CoinJoin privacy coordinator breaking UTXO lineage.",
    confidence: "HIGH",
    source: "Bitcoin Intelligence Heuristics",
    lastVerified: new Date("2026-08-01"),
    website: "https://wasabiwallet.io",
    isKycCompliant: false,
    baseRiskScore: 85,
    addresses: [
      {
        address: "bc1qwasabicoinjoin000000000000000000000000",
        chain: "bitcoin",
        label: "Wasabi Coordinator Pool",
        confidence: "HIGH",
        source: "CIOH Heuristic Engine",
        lastVerified: new Date("2026-08-01"),
      },
    ],
  },
  // 10. OKX (Exchange)
  {
    id: "ent-okx",
    name: "OKX Exchange",
    type: "EXCHANGE",
    category: "Centralized Exchange",
    description: "Global centralized cryptocurrency exchange with mandatory KYC compliance.",
    confidence: "VERIFIED",
    source: "Etherscan Label Cloud",
    lastVerified: new Date("2026-08-01"),
    website: "https://okx.com",
    isKycCompliant: true,
    baseRiskScore: 10,
    addresses: [
      {
        address: "0x6cc5f688a315f3dc28a7781717a9a798a59fda7b",
        chain: "ethereum",
        label: "OKX: Deposit Router",
        confidence: "VERIFIED",
        source: "Etherscan Label Cloud",
        lastVerified: new Date("2026-08-01"),
      },
    ],
  },
];

