import { z } from "zod";
export declare const InvestigationStatusEnum: z.ZodEnum<["queued", "processing", "completed", "failed"]>;
export type InvestigationStatus = z.infer<typeof InvestigationStatusEnum>;
export declare const InvestigationStatsSchema: z.ZodObject<{
    totalNodes: z.ZodDefault<z.ZodNumber>;
    totalEdges: z.ZodDefault<z.ZodNumber>;
    totalVolume: z.ZodDefault<z.ZodString>;
    riskScore: z.ZodDefault<z.ZodNumber>;
    detectedPatternsCount: z.ZodDefault<z.ZodNumber>;
    identifiedEntitiesCount: z.ZodDefault<z.ZodNumber>;
    evidenceCount: z.ZodDefault<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    riskScore: number;
    totalNodes: number;
    totalEdges: number;
    totalVolume: string;
    detectedPatternsCount: number;
    identifiedEntitiesCount: number;
    evidenceCount: number;
}, {
    riskScore?: number | undefined;
    totalNodes?: number | undefined;
    totalEdges?: number | undefined;
    totalVolume?: string | undefined;
    detectedPatternsCount?: number | undefined;
    identifiedEntitiesCount?: number | undefined;
    evidenceCount?: number | undefined;
}>;
export type InvestigationStats = z.infer<typeof InvestigationStatsSchema>;
export declare const InvestigationSchema: z.ZodObject<{
    id: z.ZodString;
    title: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    target: z.ZodString;
    targetType: z.ZodEnum<["address", "txHash"]>;
    chain: z.ZodString;
    direction: z.ZodDefault<z.ZodEnum<["forward", "backward", "both"]>>;
    maxHops: z.ZodDefault<z.ZodNumber>;
    status: z.ZodDefault<z.ZodEnum<["queued", "processing", "completed", "failed"]>>;
    caseNumber: z.ZodOptional<z.ZodString>;
    investigatorName: z.ZodOptional<z.ZodString>;
    createdAt: z.ZodDate;
    updatedAt: z.ZodDate;
    stats: z.ZodOptional<z.ZodObject<{
        totalNodes: z.ZodDefault<z.ZodNumber>;
        totalEdges: z.ZodDefault<z.ZodNumber>;
        totalVolume: z.ZodDefault<z.ZodString>;
        riskScore: z.ZodDefault<z.ZodNumber>;
        detectedPatternsCount: z.ZodDefault<z.ZodNumber>;
        identifiedEntitiesCount: z.ZodDefault<z.ZodNumber>;
        evidenceCount: z.ZodDefault<z.ZodNumber>;
    }, "strip", z.ZodTypeAny, {
        riskScore: number;
        totalNodes: number;
        totalEdges: number;
        totalVolume: string;
        detectedPatternsCount: number;
        identifiedEntitiesCount: number;
        evidenceCount: number;
    }, {
        riskScore?: number | undefined;
        totalNodes?: number | undefined;
        totalEdges?: number | undefined;
        totalVolume?: string | undefined;
        detectedPatternsCount?: number | undefined;
        identifiedEntitiesCount?: number | undefined;
        evidenceCount?: number | undefined;
    }>>;
    graph: z.ZodOptional<z.ZodObject<{
        nodes: z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            address: z.ZodString;
            label: z.ZodString;
            type: z.ZodDefault<z.ZodEnum<["address", "entity", "contract", "cluster"]>>;
            chain: z.ZodString;
            entityId: z.ZodOptional<z.ZodString>;
            entityName: z.ZodOptional<z.ZodString>;
            entityType: z.ZodOptional<z.ZodString>;
            riskScore: z.ZodOptional<z.ZodNumber>;
            clusterId: z.ZodOptional<z.ZodString>;
            balance: z.ZodOptional<z.ZodString>;
            formattedBalance: z.ZodOptional<z.ZodString>;
            txCount: z.ZodOptional<z.ZodNumber>;
            firstSeen: z.ZodOptional<z.ZodDate>;
            lastSeen: z.ZodOptional<z.ZodDate>;
            tags: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
            isTarget: z.ZodOptional<z.ZodBoolean>;
            isSuspect: z.ZodOptional<z.ZodBoolean>;
            hopLevel: z.ZodOptional<z.ZodNumber>;
            metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        }, "strip", z.ZodTypeAny, {
            address: string;
            type: "address" | "entity" | "contract" | "cluster";
            id: string;
            chain: string;
            label: string;
            metadata?: Record<string, unknown> | undefined;
            entityId?: string | undefined;
            entityName?: string | undefined;
            entityType?: string | undefined;
            riskScore?: number | undefined;
            clusterId?: string | undefined;
            balance?: string | undefined;
            formattedBalance?: string | undefined;
            txCount?: number | undefined;
            firstSeen?: Date | undefined;
            lastSeen?: Date | undefined;
            tags?: string[] | undefined;
            isTarget?: boolean | undefined;
            isSuspect?: boolean | undefined;
            hopLevel?: number | undefined;
        }, {
            address: string;
            id: string;
            chain: string;
            label: string;
            type?: "address" | "entity" | "contract" | "cluster" | undefined;
            metadata?: Record<string, unknown> | undefined;
            entityId?: string | undefined;
            entityName?: string | undefined;
            entityType?: string | undefined;
            riskScore?: number | undefined;
            clusterId?: string | undefined;
            balance?: string | undefined;
            formattedBalance?: string | undefined;
            txCount?: number | undefined;
            firstSeen?: Date | undefined;
            lastSeen?: Date | undefined;
            tags?: string[] | undefined;
            isTarget?: boolean | undefined;
            isSuspect?: boolean | undefined;
            hopLevel?: number | undefined;
        }>, "many">;
        edges: z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            source: z.ZodString;
            target: z.ZodString;
            txHash: z.ZodString;
            asset: z.ZodString;
            amount: z.ZodString;
            formattedAmount: z.ZodString;
            valueUsd: z.ZodOptional<z.ZodNumber>;
            timestamp: z.ZodDate;
            chain: z.ZodString;
            fee: z.ZodOptional<z.ZodString>;
            isTokenTransfer: z.ZodOptional<z.ZodBoolean>;
            tokenSymbol: z.ZodOptional<z.ZodString>;
            isContractCall: z.ZodOptional<z.ZodBoolean>;
            confidence: z.ZodDefault<z.ZodNumber>;
            isCrossChain: z.ZodOptional<z.ZodBoolean>;
            bridgeName: z.ZodOptional<z.ZodString>;
            metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        }, "strip", z.ZodTypeAny, {
            txHash: string;
            amount: string;
            formattedAmount: string;
            id: string;
            chain: string;
            timestamp: Date;
            asset: string;
            source: string;
            target: string;
            confidence: number;
            tokenSymbol?: string | undefined;
            fee?: string | undefined;
            isContractCall?: boolean | undefined;
            metadata?: Record<string, unknown> | undefined;
            valueUsd?: number | undefined;
            isTokenTransfer?: boolean | undefined;
            isCrossChain?: boolean | undefined;
            bridgeName?: string | undefined;
        }, {
            txHash: string;
            amount: string;
            formattedAmount: string;
            id: string;
            chain: string;
            timestamp: Date;
            asset: string;
            source: string;
            target: string;
            tokenSymbol?: string | undefined;
            fee?: string | undefined;
            isContractCall?: boolean | undefined;
            metadata?: Record<string, unknown> | undefined;
            valueUsd?: number | undefined;
            isTokenTransfer?: boolean | undefined;
            confidence?: number | undefined;
            isCrossChain?: boolean | undefined;
            bridgeName?: string | undefined;
        }>, "many">;
    }, "strip", z.ZodTypeAny, {
        nodes: {
            address: string;
            type: "address" | "entity" | "contract" | "cluster";
            id: string;
            chain: string;
            label: string;
            metadata?: Record<string, unknown> | undefined;
            entityId?: string | undefined;
            entityName?: string | undefined;
            entityType?: string | undefined;
            riskScore?: number | undefined;
            clusterId?: string | undefined;
            balance?: string | undefined;
            formattedBalance?: string | undefined;
            txCount?: number | undefined;
            firstSeen?: Date | undefined;
            lastSeen?: Date | undefined;
            tags?: string[] | undefined;
            isTarget?: boolean | undefined;
            isSuspect?: boolean | undefined;
            hopLevel?: number | undefined;
        }[];
        edges: {
            txHash: string;
            amount: string;
            formattedAmount: string;
            id: string;
            chain: string;
            timestamp: Date;
            asset: string;
            source: string;
            target: string;
            confidence: number;
            tokenSymbol?: string | undefined;
            fee?: string | undefined;
            isContractCall?: boolean | undefined;
            metadata?: Record<string, unknown> | undefined;
            valueUsd?: number | undefined;
            isTokenTransfer?: boolean | undefined;
            isCrossChain?: boolean | undefined;
            bridgeName?: string | undefined;
        }[];
    }, {
        nodes: {
            address: string;
            id: string;
            chain: string;
            label: string;
            type?: "address" | "entity" | "contract" | "cluster" | undefined;
            metadata?: Record<string, unknown> | undefined;
            entityId?: string | undefined;
            entityName?: string | undefined;
            entityType?: string | undefined;
            riskScore?: number | undefined;
            clusterId?: string | undefined;
            balance?: string | undefined;
            formattedBalance?: string | undefined;
            txCount?: number | undefined;
            firstSeen?: Date | undefined;
            lastSeen?: Date | undefined;
            tags?: string[] | undefined;
            isTarget?: boolean | undefined;
            isSuspect?: boolean | undefined;
            hopLevel?: number | undefined;
        }[];
        edges: {
            txHash: string;
            amount: string;
            formattedAmount: string;
            id: string;
            chain: string;
            timestamp: Date;
            asset: string;
            source: string;
            target: string;
            tokenSymbol?: string | undefined;
            fee?: string | undefined;
            isContractCall?: boolean | undefined;
            metadata?: Record<string, unknown> | undefined;
            valueUsd?: number | undefined;
            isTokenTransfer?: boolean | undefined;
            confidence?: number | undefined;
            isCrossChain?: boolean | undefined;
            bridgeName?: string | undefined;
        }[];
    }>>;
    risk: z.ZodOptional<z.ZodObject<{
        target: z.ZodString;
        targetType: z.ZodEnum<["address", "transaction", "txHash", "cluster", "investigation"]>;
        overallScore: z.ZodNumber;
        riskLevel: z.ZodEnum<["LOW", "MEDIUM", "HIGH", "CRITICAL"]>;
        factors: z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            name: z.ZodString;
            category: z.ZodString;
            scoreDelta: z.ZodNumber;
            maxPossible: z.ZodNumber;
            description: z.ZodString;
            severity: z.ZodEnum<["LOW", "MEDIUM", "HIGH", "CRITICAL"]>;
            evidenceIds: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
            evidenceChain: z.ZodDefault<z.ZodArray<z.ZodObject<{
                evidenceId: z.ZodString;
                ruleId: z.ZodString;
                patternType: z.ZodString;
                explanation: z.ZodString;
                transactionHashes: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
                wallets: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
                entityName: z.ZodOptional<z.ZodString>;
                entityType: z.ZodOptional<z.ZodString>;
                timestamp: z.ZodDate;
                severity: z.ZodString;
                confidence: z.ZodNumber;
            }, "strip", z.ZodTypeAny, {
                timestamp: Date;
                confidence: number;
                explanation: string;
                severity: string;
                transactionHashes: string[];
                ruleId: string;
                patternType: string;
                evidenceId: string;
                wallets: string[];
                entityName?: string | undefined;
                entityType?: string | undefined;
            }, {
                timestamp: Date;
                confidence: number;
                explanation: string;
                severity: string;
                ruleId: string;
                patternType: string;
                evidenceId: string;
                entityName?: string | undefined;
                entityType?: string | undefined;
                transactionHashes?: string[] | undefined;
                wallets?: string[] | undefined;
            }>, "many">>;
        }, "strip", z.ZodTypeAny, {
            id: string;
            name: string;
            category: string;
            description: string;
            severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            scoreDelta: number;
            maxPossible: number;
            evidenceIds: string[];
            evidenceChain: {
                timestamp: Date;
                confidence: number;
                explanation: string;
                severity: string;
                transactionHashes: string[];
                ruleId: string;
                patternType: string;
                evidenceId: string;
                wallets: string[];
                entityName?: string | undefined;
                entityType?: string | undefined;
            }[];
        }, {
            id: string;
            name: string;
            category: string;
            description: string;
            severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            scoreDelta: number;
            maxPossible: number;
            evidenceIds?: string[] | undefined;
            evidenceChain?: {
                timestamp: Date;
                confidence: number;
                explanation: string;
                severity: string;
                ruleId: string;
                patternType: string;
                evidenceId: string;
                entityName?: string | undefined;
                entityType?: string | undefined;
                transactionHashes?: string[] | undefined;
                wallets?: string[] | undefined;
            }[] | undefined;
        }>, "many">;
        evidenceList: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        summary: z.ZodString;
        calculatedAt: z.ZodDate;
        recommendations: z.ZodArray<z.ZodString, "many">;
        confidence: z.ZodOptional<z.ZodObject<{
            confidenceScore: z.ZodNumber;
            confidenceLevel: z.ZodEnum<["LOW", "MEDIUM", "HIGH", "VERIFIED"]>;
            strengths: z.ZodArray<z.ZodString, "many">;
            limitations: z.ZodArray<z.ZodString, "many">;
        }, "strip", z.ZodTypeAny, {
            confidenceScore: number;
            confidenceLevel: "LOW" | "MEDIUM" | "HIGH" | "VERIFIED";
            strengths: string[];
            limitations: string[];
        }, {
            confidenceScore: number;
            confidenceLevel: "LOW" | "MEDIUM" | "HIGH" | "VERIFIED";
            strengths: string[];
            limitations: string[];
        }>>;
    }, "strip", z.ZodTypeAny, {
        target: string;
        targetType: "txHash" | "address" | "cluster" | "transaction" | "investigation";
        overallScore: number;
        riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        factors: {
            id: string;
            name: string;
            category: string;
            description: string;
            severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            scoreDelta: number;
            maxPossible: number;
            evidenceIds: string[];
            evidenceChain: {
                timestamp: Date;
                confidence: number;
                explanation: string;
                severity: string;
                transactionHashes: string[];
                ruleId: string;
                patternType: string;
                evidenceId: string;
                wallets: string[];
                entityName?: string | undefined;
                entityType?: string | undefined;
            }[];
        }[];
        evidenceList: string[];
        summary: string;
        calculatedAt: Date;
        recommendations: string[];
        confidence?: {
            confidenceScore: number;
            confidenceLevel: "LOW" | "MEDIUM" | "HIGH" | "VERIFIED";
            strengths: string[];
            limitations: string[];
        } | undefined;
    }, {
        target: string;
        targetType: "txHash" | "address" | "cluster" | "transaction" | "investigation";
        overallScore: number;
        riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        factors: {
            id: string;
            name: string;
            category: string;
            description: string;
            severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            scoreDelta: number;
            maxPossible: number;
            evidenceIds?: string[] | undefined;
            evidenceChain?: {
                timestamp: Date;
                confidence: number;
                explanation: string;
                severity: string;
                ruleId: string;
                patternType: string;
                evidenceId: string;
                entityName?: string | undefined;
                entityType?: string | undefined;
                transactionHashes?: string[] | undefined;
                wallets?: string[] | undefined;
            }[] | undefined;
        }[];
        summary: string;
        calculatedAt: Date;
        recommendations: string[];
        confidence?: {
            confidenceScore: number;
            confidenceLevel: "LOW" | "MEDIUM" | "HIGH" | "VERIFIED";
            strengths: string[];
            limitations: string[];
        } | undefined;
        evidenceList?: string[] | undefined;
    }>>;
    patterns: z.ZodOptional<z.ZodArray<z.ZodObject<{
        ruleId: z.ZodString;
        patternType: z.ZodEnum<["FAN_OUT", "FAN_IN", "RAPID_MOVEMENT", "PEEL_CHAIN", "HIGH_HOP_MOVEMENT", "MIXER_INTERACTION", "BRIDGE_INTERACTION", "ILLICIT_INTERACTION", "CIRCULAR_FLOW", "STRUCTURING"]>;
        title: z.ZodString;
        description: z.ZodString;
        severity: z.ZodNumber;
        confidence: z.ZodNumber;
        evidence: z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            type: z.ZodString;
            title: z.ZodString;
            description: z.ZodString;
            confidence: z.ZodNumber;
            severity: z.ZodEnum<["LOW", "MEDIUM", "HIGH", "CRITICAL"]>;
            source: z.ZodOptional<z.ZodString>;
            timestamp: z.ZodDate;
            transactionHashes: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
            addresses: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
            metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        }, "strip", z.ZodTypeAny, {
            type: string;
            id: string;
            timestamp: Date;
            confidence: number;
            description: string;
            addresses: string[];
            title: string;
            severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            transactionHashes: string[];
            metadata?: Record<string, unknown> | undefined;
            source?: string | undefined;
        }, {
            type: string;
            id: string;
            timestamp: Date;
            confidence: number;
            description: string;
            title: string;
            severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            metadata?: Record<string, unknown> | undefined;
            source?: string | undefined;
            addresses?: string[] | undefined;
            transactionHashes?: string[] | undefined;
        }>, "many">;
        affectedAddresses: z.ZodArray<z.ZodString, "many">;
        affectedTxHashes: z.ZodArray<z.ZodString, "many">;
        metrics: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    }, "strip", z.ZodTypeAny, {
        confidence: number;
        description: string;
        title: string;
        severity: number;
        ruleId: string;
        patternType: "FAN_OUT" | "FAN_IN" | "RAPID_MOVEMENT" | "PEEL_CHAIN" | "HIGH_HOP_MOVEMENT" | "MIXER_INTERACTION" | "BRIDGE_INTERACTION" | "ILLICIT_INTERACTION" | "CIRCULAR_FLOW" | "STRUCTURING";
        evidence: {
            type: string;
            id: string;
            timestamp: Date;
            confidence: number;
            description: string;
            addresses: string[];
            title: string;
            severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            transactionHashes: string[];
            metadata?: Record<string, unknown> | undefined;
            source?: string | undefined;
        }[];
        affectedAddresses: string[];
        affectedTxHashes: string[];
        metrics?: Record<string, unknown> | undefined;
    }, {
        confidence: number;
        description: string;
        title: string;
        severity: number;
        ruleId: string;
        patternType: "FAN_OUT" | "FAN_IN" | "RAPID_MOVEMENT" | "PEEL_CHAIN" | "HIGH_HOP_MOVEMENT" | "MIXER_INTERACTION" | "BRIDGE_INTERACTION" | "ILLICIT_INTERACTION" | "CIRCULAR_FLOW" | "STRUCTURING";
        evidence: {
            type: string;
            id: string;
            timestamp: Date;
            confidence: number;
            description: string;
            title: string;
            severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            metadata?: Record<string, unknown> | undefined;
            source?: string | undefined;
            addresses?: string[] | undefined;
            transactionHashes?: string[] | undefined;
        }[];
        affectedAddresses: string[];
        affectedTxHashes: string[];
        metrics?: Record<string, unknown> | undefined;
    }>, "many">>;
    alternativeExplanations: z.ZodOptional<z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        patternType: z.ZodEnum<["FAN_OUT", "FAN_IN", "RAPID_MOVEMENT", "PEEL_CHAIN", "HIGH_HOP_MOVEMENT", "MIXER_INTERACTION", "BRIDGE_INTERACTION", "ILLICIT_INTERACTION", "CIRCULAR_FLOW", "STRUCTURING"]>;
        patternTitle: z.ZodString;
        suspiciousInterpretation: z.ZodString;
        alternativeExplanations: z.ZodArray<z.ZodObject<{
            label: z.ZodString;
            description: z.ZodString;
            likelihood: z.ZodEnum<["LOW", "MEDIUM", "HIGH"]>;
            category: z.ZodEnum<["LEGITIMATE_BUSINESS", "DEFI_ACTIVITY", "PRIVACY", "OPERATIONAL", "REGULATORY"]>;
        }, "strip", z.ZodTypeAny, {
            label: string;
            category: "LEGITIMATE_BUSINESS" | "DEFI_ACTIVITY" | "PRIVACY" | "OPERATIONAL" | "REGULATORY";
            description: string;
            likelihood: "LOW" | "MEDIUM" | "HIGH";
        }, {
            label: string;
            category: "LEGITIMATE_BUSINESS" | "DEFI_ACTIVITY" | "PRIVACY" | "OPERATIONAL" | "REGULATORY";
            description: string;
            likelihood: "LOW" | "MEDIUM" | "HIGH";
        }>, "many">;
        investigatorGuidance: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        id: string;
        patternType: "FAN_OUT" | "FAN_IN" | "RAPID_MOVEMENT" | "PEEL_CHAIN" | "HIGH_HOP_MOVEMENT" | "MIXER_INTERACTION" | "BRIDGE_INTERACTION" | "ILLICIT_INTERACTION" | "CIRCULAR_FLOW" | "STRUCTURING";
        patternTitle: string;
        suspiciousInterpretation: string;
        alternativeExplanations: {
            label: string;
            category: "LEGITIMATE_BUSINESS" | "DEFI_ACTIVITY" | "PRIVACY" | "OPERATIONAL" | "REGULATORY";
            description: string;
            likelihood: "LOW" | "MEDIUM" | "HIGH";
        }[];
        investigatorGuidance: string;
    }, {
        id: string;
        patternType: "FAN_OUT" | "FAN_IN" | "RAPID_MOVEMENT" | "PEEL_CHAIN" | "HIGH_HOP_MOVEMENT" | "MIXER_INTERACTION" | "BRIDGE_INTERACTION" | "ILLICIT_INTERACTION" | "CIRCULAR_FLOW" | "STRUCTURING";
        patternTitle: string;
        suspiciousInterpretation: string;
        alternativeExplanations: {
            label: string;
            category: "LEGITIMATE_BUSINESS" | "DEFI_ACTIVITY" | "PRIVACY" | "OPERATIONAL" | "REGULATORY";
            description: string;
            likelihood: "LOW" | "MEDIUM" | "HIGH";
        }[];
        investigatorGuidance: string;
    }>, "many">>;
    entities: z.ZodOptional<z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        name: z.ZodString;
        type: z.ZodEnum<["EXCHANGE", "MIXER", "BRIDGE", "MARKETPLACE", "GAMBLING", "SCAM", "KNOWN_ILLICIT", "SERVICE", "UNKNOWN"]>;
        category: z.ZodOptional<z.ZodString>;
        description: z.ZodOptional<z.ZodString>;
        addresses: z.ZodArray<z.ZodObject<{
            address: z.ZodString;
            chain: z.ZodString;
            label: z.ZodOptional<z.ZodString>;
            confidence: z.ZodDefault<z.ZodEnum<["LOW", "MEDIUM", "HIGH", "VERIFIED"]>>;
            source: z.ZodString;
            lastVerified: z.ZodDate;
        }, "strip", z.ZodTypeAny, {
            address: string;
            chain: string;
            source: string;
            confidence: "LOW" | "MEDIUM" | "HIGH" | "VERIFIED";
            lastVerified: Date;
            label?: string | undefined;
        }, {
            address: string;
            chain: string;
            source: string;
            lastVerified: Date;
            label?: string | undefined;
            confidence?: "LOW" | "MEDIUM" | "HIGH" | "VERIFIED" | undefined;
        }>, "many">;
        confidence: z.ZodEnum<["LOW", "MEDIUM", "HIGH", "VERIFIED"]>;
        source: z.ZodString;
        lastVerified: z.ZodDate;
        website: z.ZodOptional<z.ZodString>;
        jurisdiction: z.ZodOptional<z.ZodString>;
        isKycCompliant: z.ZodOptional<z.ZodBoolean>;
        baseRiskScore: z.ZodDefault<z.ZodNumber>;
    }, "strip", z.ZodTypeAny, {
        type: "EXCHANGE" | "MIXER" | "BRIDGE" | "MARKETPLACE" | "GAMBLING" | "SCAM" | "KNOWN_ILLICIT" | "SERVICE" | "UNKNOWN";
        id: string;
        source: string;
        confidence: "LOW" | "MEDIUM" | "HIGH" | "VERIFIED";
        lastVerified: Date;
        name: string;
        addresses: {
            address: string;
            chain: string;
            source: string;
            confidence: "LOW" | "MEDIUM" | "HIGH" | "VERIFIED";
            lastVerified: Date;
            label?: string | undefined;
        }[];
        baseRiskScore: number;
        category?: string | undefined;
        description?: string | undefined;
        website?: string | undefined;
        jurisdiction?: string | undefined;
        isKycCompliant?: boolean | undefined;
    }, {
        type: "EXCHANGE" | "MIXER" | "BRIDGE" | "MARKETPLACE" | "GAMBLING" | "SCAM" | "KNOWN_ILLICIT" | "SERVICE" | "UNKNOWN";
        id: string;
        source: string;
        confidence: "LOW" | "MEDIUM" | "HIGH" | "VERIFIED";
        lastVerified: Date;
        name: string;
        addresses: {
            address: string;
            chain: string;
            source: string;
            lastVerified: Date;
            label?: string | undefined;
            confidence?: "LOW" | "MEDIUM" | "HIGH" | "VERIFIED" | undefined;
        }[];
        category?: string | undefined;
        description?: string | undefined;
        website?: string | undefined;
        jurisdiction?: string | undefined;
        isKycCompliant?: boolean | undefined;
        baseRiskScore?: number | undefined;
    }>, "many">>;
    clusters: z.ZodOptional<z.ZodArray<z.ZodObject<{
        clusterId: z.ZodString;
        name: z.ZodOptional<z.ZodString>;
        members: z.ZodArray<z.ZodString, "many">;
        primaryAddress: z.ZodOptional<z.ZodString>;
        confidence: z.ZodNumber;
        signals: z.ZodArray<z.ZodString, "many">;
        detailedSignals: z.ZodOptional<z.ZodArray<z.ZodObject<{
            type: z.ZodString;
            description: z.ZodString;
            confidence: z.ZodNumber;
            txHashes: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
        }, "strip", z.ZodTypeAny, {
            type: string;
            confidence: number;
            description: string;
            txHashes?: string[] | undefined;
        }, {
            type: string;
            confidence: number;
            description: string;
            txHashes?: string[] | undefined;
        }>, "many">>;
        chain: z.ZodString;
        totalTxCount: z.ZodOptional<z.ZodNumber>;
        createdAt: z.ZodDate;
        tags: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    }, "strip", z.ZodTypeAny, {
        chain: string;
        clusterId: string;
        confidence: number;
        members: string[];
        signals: string[];
        createdAt: Date;
        tags?: string[] | undefined;
        name?: string | undefined;
        primaryAddress?: string | undefined;
        detailedSignals?: {
            type: string;
            confidence: number;
            description: string;
            txHashes?: string[] | undefined;
        }[] | undefined;
        totalTxCount?: number | undefined;
    }, {
        chain: string;
        clusterId: string;
        confidence: number;
        members: string[];
        signals: string[];
        createdAt: Date;
        tags?: string[] | undefined;
        name?: string | undefined;
        primaryAddress?: string | undefined;
        detailedSignals?: {
            type: string;
            confidence: number;
            description: string;
            txHashes?: string[] | undefined;
        }[] | undefined;
        totalTxCount?: number | undefined;
    }>, "many">>;
    evidence: z.ZodOptional<z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        type: z.ZodString;
        title: z.ZodString;
        description: z.ZodString;
        confidence: z.ZodNumber;
        severity: z.ZodEnum<["LOW", "MEDIUM", "HIGH", "CRITICAL"]>;
        source: z.ZodOptional<z.ZodString>;
        timestamp: z.ZodDate;
        transactionHashes: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        addresses: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    }, "strip", z.ZodTypeAny, {
        type: string;
        id: string;
        timestamp: Date;
        confidence: number;
        description: string;
        addresses: string[];
        title: string;
        severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        transactionHashes: string[];
        metadata?: Record<string, unknown> | undefined;
        source?: string | undefined;
    }, {
        type: string;
        id: string;
        timestamp: Date;
        confidence: number;
        description: string;
        title: string;
        severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        metadata?: Record<string, unknown> | undefined;
        source?: string | undefined;
        addresses?: string[] | undefined;
        transactionHashes?: string[] | undefined;
    }>, "many">>;
    attributions: z.ZodOptional<z.ZodArray<z.ZodObject<{
        address: z.ZodString;
        entityId: z.ZodOptional<z.ZodString>;
        entityName: z.ZodOptional<z.ZodString>;
        entityType: z.ZodOptional<z.ZodEnum<["EXCHANGE", "MIXER", "BRIDGE", "MARKETPLACE", "GAMBLING", "SCAM", "KNOWN_ILLICIT", "SERVICE", "UNKNOWN"]>>;
        attributionType: z.ZodEnum<["OBSERVED", "INFERENCE", "ATTRIBUTION"]>;
        confidence: z.ZodNumber;
        explanation: z.ZodString;
        supportingEvidenceIds: z.ZodArray<z.ZodString, "many">;
    }, "strip", z.ZodTypeAny, {
        address: string;
        confidence: number;
        attributionType: "OBSERVED" | "INFERENCE" | "ATTRIBUTION";
        explanation: string;
        supportingEvidenceIds: string[];
        entityId?: string | undefined;
        entityName?: string | undefined;
        entityType?: "EXCHANGE" | "MIXER" | "BRIDGE" | "MARKETPLACE" | "GAMBLING" | "SCAM" | "KNOWN_ILLICIT" | "SERVICE" | "UNKNOWN" | undefined;
    }, {
        address: string;
        confidence: number;
        attributionType: "OBSERVED" | "INFERENCE" | "ATTRIBUTION";
        explanation: string;
        supportingEvidenceIds: string[];
        entityId?: string | undefined;
        entityName?: string | undefined;
        entityType?: "EXCHANGE" | "MIXER" | "BRIDGE" | "MARKETPLACE" | "GAMBLING" | "SCAM" | "KNOWN_ILLICIT" | "SERVICE" | "UNKNOWN" | undefined;
    }>, "many">>;
    timeline: z.ZodOptional<z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        timestamp: z.ZodDate;
        eventType: z.ZodEnum<["INITIAL_FUNDS", "LARGE_TRANSFER", "FAN_OUT", "FAN_IN", "MIXER_INTERACTION", "BRIDGE_INTERACTION", "RAPID_ACTIVITY", "HIGH_HOP_LAYERING", "EXCHANGE_INTERACTION", "PEEL_CHAIN"]>;
        title: z.ZodString;
        description: z.ZodString;
        sourceAddress: z.ZodOptional<z.ZodString>;
        sourceEntity: z.ZodOptional<z.ZodString>;
        destinationAddress: z.ZodOptional<z.ZodString>;
        destinationEntity: z.ZodOptional<z.ZodString>;
        txHash: z.ZodOptional<z.ZodString>;
        amount: z.ZodOptional<z.ZodString>;
        asset: z.ZodOptional<z.ZodString>;
        patternType: z.ZodOptional<z.ZodEnum<["FAN_OUT", "FAN_IN", "RAPID_MOVEMENT", "PEEL_CHAIN", "HIGH_HOP_MOVEMENT", "MIXER_INTERACTION", "BRIDGE_INTERACTION", "ILLICIT_INTERACTION", "CIRCULAR_FLOW", "STRUCTURING"]>>;
        severity: z.ZodEnum<["LOW", "MEDIUM", "HIGH", "CRITICAL"]>;
        relatedNodeIds: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        relatedEdgeIds: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    }, "strip", z.ZodTypeAny, {
        id: string;
        timestamp: Date;
        description: string;
        title: string;
        severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        eventType: "FAN_OUT" | "FAN_IN" | "PEEL_CHAIN" | "MIXER_INTERACTION" | "BRIDGE_INTERACTION" | "INITIAL_FUNDS" | "LARGE_TRANSFER" | "RAPID_ACTIVITY" | "HIGH_HOP_LAYERING" | "EXCHANGE_INTERACTION";
        relatedNodeIds: string[];
        relatedEdgeIds: string[];
        txHash?: string | undefined;
        amount?: string | undefined;
        asset?: string | undefined;
        patternType?: "FAN_OUT" | "FAN_IN" | "RAPID_MOVEMENT" | "PEEL_CHAIN" | "HIGH_HOP_MOVEMENT" | "MIXER_INTERACTION" | "BRIDGE_INTERACTION" | "ILLICIT_INTERACTION" | "CIRCULAR_FLOW" | "STRUCTURING" | undefined;
        sourceAddress?: string | undefined;
        sourceEntity?: string | undefined;
        destinationAddress?: string | undefined;
        destinationEntity?: string | undefined;
    }, {
        id: string;
        timestamp: Date;
        description: string;
        title: string;
        severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        eventType: "FAN_OUT" | "FAN_IN" | "PEEL_CHAIN" | "MIXER_INTERACTION" | "BRIDGE_INTERACTION" | "INITIAL_FUNDS" | "LARGE_TRANSFER" | "RAPID_ACTIVITY" | "HIGH_HOP_LAYERING" | "EXCHANGE_INTERACTION";
        txHash?: string | undefined;
        amount?: string | undefined;
        asset?: string | undefined;
        patternType?: "FAN_OUT" | "FAN_IN" | "RAPID_MOVEMENT" | "PEEL_CHAIN" | "HIGH_HOP_MOVEMENT" | "MIXER_INTERACTION" | "BRIDGE_INTERACTION" | "ILLICIT_INTERACTION" | "CIRCULAR_FLOW" | "STRUCTURING" | undefined;
        sourceAddress?: string | undefined;
        sourceEntity?: string | undefined;
        destinationAddress?: string | undefined;
        destinationEntity?: string | undefined;
        relatedNodeIds?: string[] | undefined;
        relatedEdgeIds?: string[] | undefined;
    }>, "many">>;
}, "strip", z.ZodTypeAny, {
    status: "failed" | "queued" | "processing" | "completed";
    id: string;
    chain: string;
    target: string;
    title: string;
    createdAt: Date;
    targetType: "txHash" | "address";
    direction: "forward" | "backward" | "both";
    maxHops: number;
    updatedAt: Date;
    description?: string | undefined;
    evidence?: {
        type: string;
        id: string;
        timestamp: Date;
        confidence: number;
        description: string;
        addresses: string[];
        title: string;
        severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        transactionHashes: string[];
        metadata?: Record<string, unknown> | undefined;
        source?: string | undefined;
    }[] | undefined;
    alternativeExplanations?: {
        id: string;
        patternType: "FAN_OUT" | "FAN_IN" | "RAPID_MOVEMENT" | "PEEL_CHAIN" | "HIGH_HOP_MOVEMENT" | "MIXER_INTERACTION" | "BRIDGE_INTERACTION" | "ILLICIT_INTERACTION" | "CIRCULAR_FLOW" | "STRUCTURING";
        patternTitle: string;
        suspiciousInterpretation: string;
        alternativeExplanations: {
            label: string;
            category: "LEGITIMATE_BUSINESS" | "DEFI_ACTIVITY" | "PRIVACY" | "OPERATIONAL" | "REGULATORY";
            description: string;
            likelihood: "LOW" | "MEDIUM" | "HIGH";
        }[];
        investigatorGuidance: string;
    }[] | undefined;
    caseNumber?: string | undefined;
    investigatorName?: string | undefined;
    stats?: {
        riskScore: number;
        totalNodes: number;
        totalEdges: number;
        totalVolume: string;
        detectedPatternsCount: number;
        identifiedEntitiesCount: number;
        evidenceCount: number;
    } | undefined;
    graph?: {
        nodes: {
            address: string;
            type: "address" | "entity" | "contract" | "cluster";
            id: string;
            chain: string;
            label: string;
            metadata?: Record<string, unknown> | undefined;
            entityId?: string | undefined;
            entityName?: string | undefined;
            entityType?: string | undefined;
            riskScore?: number | undefined;
            clusterId?: string | undefined;
            balance?: string | undefined;
            formattedBalance?: string | undefined;
            txCount?: number | undefined;
            firstSeen?: Date | undefined;
            lastSeen?: Date | undefined;
            tags?: string[] | undefined;
            isTarget?: boolean | undefined;
            isSuspect?: boolean | undefined;
            hopLevel?: number | undefined;
        }[];
        edges: {
            txHash: string;
            amount: string;
            formattedAmount: string;
            id: string;
            chain: string;
            timestamp: Date;
            asset: string;
            source: string;
            target: string;
            confidence: number;
            tokenSymbol?: string | undefined;
            fee?: string | undefined;
            isContractCall?: boolean | undefined;
            metadata?: Record<string, unknown> | undefined;
            valueUsd?: number | undefined;
            isTokenTransfer?: boolean | undefined;
            isCrossChain?: boolean | undefined;
            bridgeName?: string | undefined;
        }[];
    } | undefined;
    risk?: {
        target: string;
        targetType: "txHash" | "address" | "cluster" | "transaction" | "investigation";
        overallScore: number;
        riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        factors: {
            id: string;
            name: string;
            category: string;
            description: string;
            severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            scoreDelta: number;
            maxPossible: number;
            evidenceIds: string[];
            evidenceChain: {
                timestamp: Date;
                confidence: number;
                explanation: string;
                severity: string;
                transactionHashes: string[];
                ruleId: string;
                patternType: string;
                evidenceId: string;
                wallets: string[];
                entityName?: string | undefined;
                entityType?: string | undefined;
            }[];
        }[];
        evidenceList: string[];
        summary: string;
        calculatedAt: Date;
        recommendations: string[];
        confidence?: {
            confidenceScore: number;
            confidenceLevel: "LOW" | "MEDIUM" | "HIGH" | "VERIFIED";
            strengths: string[];
            limitations: string[];
        } | undefined;
    } | undefined;
    patterns?: {
        confidence: number;
        description: string;
        title: string;
        severity: number;
        ruleId: string;
        patternType: "FAN_OUT" | "FAN_IN" | "RAPID_MOVEMENT" | "PEEL_CHAIN" | "HIGH_HOP_MOVEMENT" | "MIXER_INTERACTION" | "BRIDGE_INTERACTION" | "ILLICIT_INTERACTION" | "CIRCULAR_FLOW" | "STRUCTURING";
        evidence: {
            type: string;
            id: string;
            timestamp: Date;
            confidence: number;
            description: string;
            addresses: string[];
            title: string;
            severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            transactionHashes: string[];
            metadata?: Record<string, unknown> | undefined;
            source?: string | undefined;
        }[];
        affectedAddresses: string[];
        affectedTxHashes: string[];
        metrics?: Record<string, unknown> | undefined;
    }[] | undefined;
    entities?: {
        type: "EXCHANGE" | "MIXER" | "BRIDGE" | "MARKETPLACE" | "GAMBLING" | "SCAM" | "KNOWN_ILLICIT" | "SERVICE" | "UNKNOWN";
        id: string;
        source: string;
        confidence: "LOW" | "MEDIUM" | "HIGH" | "VERIFIED";
        lastVerified: Date;
        name: string;
        addresses: {
            address: string;
            chain: string;
            source: string;
            confidence: "LOW" | "MEDIUM" | "HIGH" | "VERIFIED";
            lastVerified: Date;
            label?: string | undefined;
        }[];
        baseRiskScore: number;
        category?: string | undefined;
        description?: string | undefined;
        website?: string | undefined;
        jurisdiction?: string | undefined;
        isKycCompliant?: boolean | undefined;
    }[] | undefined;
    clusters?: {
        chain: string;
        clusterId: string;
        confidence: number;
        members: string[];
        signals: string[];
        createdAt: Date;
        tags?: string[] | undefined;
        name?: string | undefined;
        primaryAddress?: string | undefined;
        detailedSignals?: {
            type: string;
            confidence: number;
            description: string;
            txHashes?: string[] | undefined;
        }[] | undefined;
        totalTxCount?: number | undefined;
    }[] | undefined;
    attributions?: {
        address: string;
        confidence: number;
        attributionType: "OBSERVED" | "INFERENCE" | "ATTRIBUTION";
        explanation: string;
        supportingEvidenceIds: string[];
        entityId?: string | undefined;
        entityName?: string | undefined;
        entityType?: "EXCHANGE" | "MIXER" | "BRIDGE" | "MARKETPLACE" | "GAMBLING" | "SCAM" | "KNOWN_ILLICIT" | "SERVICE" | "UNKNOWN" | undefined;
    }[] | undefined;
    timeline?: {
        id: string;
        timestamp: Date;
        description: string;
        title: string;
        severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        eventType: "FAN_OUT" | "FAN_IN" | "PEEL_CHAIN" | "MIXER_INTERACTION" | "BRIDGE_INTERACTION" | "INITIAL_FUNDS" | "LARGE_TRANSFER" | "RAPID_ACTIVITY" | "HIGH_HOP_LAYERING" | "EXCHANGE_INTERACTION";
        relatedNodeIds: string[];
        relatedEdgeIds: string[];
        txHash?: string | undefined;
        amount?: string | undefined;
        asset?: string | undefined;
        patternType?: "FAN_OUT" | "FAN_IN" | "RAPID_MOVEMENT" | "PEEL_CHAIN" | "HIGH_HOP_MOVEMENT" | "MIXER_INTERACTION" | "BRIDGE_INTERACTION" | "ILLICIT_INTERACTION" | "CIRCULAR_FLOW" | "STRUCTURING" | undefined;
        sourceAddress?: string | undefined;
        sourceEntity?: string | undefined;
        destinationAddress?: string | undefined;
        destinationEntity?: string | undefined;
    }[] | undefined;
}, {
    id: string;
    chain: string;
    target: string;
    title: string;
    createdAt: Date;
    targetType: "txHash" | "address";
    updatedAt: Date;
    status?: "failed" | "queued" | "processing" | "completed" | undefined;
    description?: string | undefined;
    evidence?: {
        type: string;
        id: string;
        timestamp: Date;
        confidence: number;
        description: string;
        title: string;
        severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        metadata?: Record<string, unknown> | undefined;
        source?: string | undefined;
        addresses?: string[] | undefined;
        transactionHashes?: string[] | undefined;
    }[] | undefined;
    alternativeExplanations?: {
        id: string;
        patternType: "FAN_OUT" | "FAN_IN" | "RAPID_MOVEMENT" | "PEEL_CHAIN" | "HIGH_HOP_MOVEMENT" | "MIXER_INTERACTION" | "BRIDGE_INTERACTION" | "ILLICIT_INTERACTION" | "CIRCULAR_FLOW" | "STRUCTURING";
        patternTitle: string;
        suspiciousInterpretation: string;
        alternativeExplanations: {
            label: string;
            category: "LEGITIMATE_BUSINESS" | "DEFI_ACTIVITY" | "PRIVACY" | "OPERATIONAL" | "REGULATORY";
            description: string;
            likelihood: "LOW" | "MEDIUM" | "HIGH";
        }[];
        investigatorGuidance: string;
    }[] | undefined;
    direction?: "forward" | "backward" | "both" | undefined;
    maxHops?: number | undefined;
    caseNumber?: string | undefined;
    investigatorName?: string | undefined;
    stats?: {
        riskScore?: number | undefined;
        totalNodes?: number | undefined;
        totalEdges?: number | undefined;
        totalVolume?: string | undefined;
        detectedPatternsCount?: number | undefined;
        identifiedEntitiesCount?: number | undefined;
        evidenceCount?: number | undefined;
    } | undefined;
    graph?: {
        nodes: {
            address: string;
            id: string;
            chain: string;
            label: string;
            type?: "address" | "entity" | "contract" | "cluster" | undefined;
            metadata?: Record<string, unknown> | undefined;
            entityId?: string | undefined;
            entityName?: string | undefined;
            entityType?: string | undefined;
            riskScore?: number | undefined;
            clusterId?: string | undefined;
            balance?: string | undefined;
            formattedBalance?: string | undefined;
            txCount?: number | undefined;
            firstSeen?: Date | undefined;
            lastSeen?: Date | undefined;
            tags?: string[] | undefined;
            isTarget?: boolean | undefined;
            isSuspect?: boolean | undefined;
            hopLevel?: number | undefined;
        }[];
        edges: {
            txHash: string;
            amount: string;
            formattedAmount: string;
            id: string;
            chain: string;
            timestamp: Date;
            asset: string;
            source: string;
            target: string;
            tokenSymbol?: string | undefined;
            fee?: string | undefined;
            isContractCall?: boolean | undefined;
            metadata?: Record<string, unknown> | undefined;
            valueUsd?: number | undefined;
            isTokenTransfer?: boolean | undefined;
            confidence?: number | undefined;
            isCrossChain?: boolean | undefined;
            bridgeName?: string | undefined;
        }[];
    } | undefined;
    risk?: {
        target: string;
        targetType: "txHash" | "address" | "cluster" | "transaction" | "investigation";
        overallScore: number;
        riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        factors: {
            id: string;
            name: string;
            category: string;
            description: string;
            severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            scoreDelta: number;
            maxPossible: number;
            evidenceIds?: string[] | undefined;
            evidenceChain?: {
                timestamp: Date;
                confidence: number;
                explanation: string;
                severity: string;
                ruleId: string;
                patternType: string;
                evidenceId: string;
                entityName?: string | undefined;
                entityType?: string | undefined;
                transactionHashes?: string[] | undefined;
                wallets?: string[] | undefined;
            }[] | undefined;
        }[];
        summary: string;
        calculatedAt: Date;
        recommendations: string[];
        confidence?: {
            confidenceScore: number;
            confidenceLevel: "LOW" | "MEDIUM" | "HIGH" | "VERIFIED";
            strengths: string[];
            limitations: string[];
        } | undefined;
        evidenceList?: string[] | undefined;
    } | undefined;
    patterns?: {
        confidence: number;
        description: string;
        title: string;
        severity: number;
        ruleId: string;
        patternType: "FAN_OUT" | "FAN_IN" | "RAPID_MOVEMENT" | "PEEL_CHAIN" | "HIGH_HOP_MOVEMENT" | "MIXER_INTERACTION" | "BRIDGE_INTERACTION" | "ILLICIT_INTERACTION" | "CIRCULAR_FLOW" | "STRUCTURING";
        evidence: {
            type: string;
            id: string;
            timestamp: Date;
            confidence: number;
            description: string;
            title: string;
            severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            metadata?: Record<string, unknown> | undefined;
            source?: string | undefined;
            addresses?: string[] | undefined;
            transactionHashes?: string[] | undefined;
        }[];
        affectedAddresses: string[];
        affectedTxHashes: string[];
        metrics?: Record<string, unknown> | undefined;
    }[] | undefined;
    entities?: {
        type: "EXCHANGE" | "MIXER" | "BRIDGE" | "MARKETPLACE" | "GAMBLING" | "SCAM" | "KNOWN_ILLICIT" | "SERVICE" | "UNKNOWN";
        id: string;
        source: string;
        confidence: "LOW" | "MEDIUM" | "HIGH" | "VERIFIED";
        lastVerified: Date;
        name: string;
        addresses: {
            address: string;
            chain: string;
            source: string;
            lastVerified: Date;
            label?: string | undefined;
            confidence?: "LOW" | "MEDIUM" | "HIGH" | "VERIFIED" | undefined;
        }[];
        category?: string | undefined;
        description?: string | undefined;
        website?: string | undefined;
        jurisdiction?: string | undefined;
        isKycCompliant?: boolean | undefined;
        baseRiskScore?: number | undefined;
    }[] | undefined;
    clusters?: {
        chain: string;
        clusterId: string;
        confidence: number;
        members: string[];
        signals: string[];
        createdAt: Date;
        tags?: string[] | undefined;
        name?: string | undefined;
        primaryAddress?: string | undefined;
        detailedSignals?: {
            type: string;
            confidence: number;
            description: string;
            txHashes?: string[] | undefined;
        }[] | undefined;
        totalTxCount?: number | undefined;
    }[] | undefined;
    attributions?: {
        address: string;
        confidence: number;
        attributionType: "OBSERVED" | "INFERENCE" | "ATTRIBUTION";
        explanation: string;
        supportingEvidenceIds: string[];
        entityId?: string | undefined;
        entityName?: string | undefined;
        entityType?: "EXCHANGE" | "MIXER" | "BRIDGE" | "MARKETPLACE" | "GAMBLING" | "SCAM" | "KNOWN_ILLICIT" | "SERVICE" | "UNKNOWN" | undefined;
    }[] | undefined;
    timeline?: {
        id: string;
        timestamp: Date;
        description: string;
        title: string;
        severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        eventType: "FAN_OUT" | "FAN_IN" | "PEEL_CHAIN" | "MIXER_INTERACTION" | "BRIDGE_INTERACTION" | "INITIAL_FUNDS" | "LARGE_TRANSFER" | "RAPID_ACTIVITY" | "HIGH_HOP_LAYERING" | "EXCHANGE_INTERACTION";
        txHash?: string | undefined;
        amount?: string | undefined;
        asset?: string | undefined;
        patternType?: "FAN_OUT" | "FAN_IN" | "RAPID_MOVEMENT" | "PEEL_CHAIN" | "HIGH_HOP_MOVEMENT" | "MIXER_INTERACTION" | "BRIDGE_INTERACTION" | "ILLICIT_INTERACTION" | "CIRCULAR_FLOW" | "STRUCTURING" | undefined;
        sourceAddress?: string | undefined;
        sourceEntity?: string | undefined;
        destinationAddress?: string | undefined;
        destinationEntity?: string | undefined;
        relatedNodeIds?: string[] | undefined;
        relatedEdgeIds?: string[] | undefined;
    }[] | undefined;
}>;
export type Investigation = z.infer<typeof InvestigationSchema>;
export declare const CreateInvestigationRequestSchema: z.ZodObject<{
    target: z.ZodString;
    chain: z.ZodDefault<z.ZodString>;
    mode: z.ZodDefault<z.ZodEnum<["live", "demo"]>>;
    direction: z.ZodDefault<z.ZodEnum<["forward", "backward", "both"]>>;
    maxHops: z.ZodDefault<z.ZodNumber>;
    title: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    caseNumber: z.ZodOptional<z.ZodString>;
    investigatorName: z.ZodOptional<z.ZodString>;
    minTransferValue: z.ZodOptional<z.ZodString>;
    asset: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    chain: string;
    target: string;
    direction: "forward" | "backward" | "both";
    maxHops: number;
    mode: "live" | "demo";
    asset?: string | undefined;
    description?: string | undefined;
    title?: string | undefined;
    caseNumber?: string | undefined;
    investigatorName?: string | undefined;
    minTransferValue?: string | undefined;
}, {
    target: string;
    chain?: string | undefined;
    asset?: string | undefined;
    description?: string | undefined;
    title?: string | undefined;
    direction?: "forward" | "backward" | "both" | undefined;
    maxHops?: number | undefined;
    caseNumber?: string | undefined;
    investigatorName?: string | undefined;
    mode?: "live" | "demo" | undefined;
    minTransferValue?: string | undefined;
}>;
export type CreateInvestigationRequest = z.infer<typeof CreateInvestigationRequestSchema>;
export declare const SubpoenaRecommendationSchema: z.ZodObject<{
    entityName: z.ZodString;
    entityType: z.ZodString;
    address: z.ZodString;
    jurisdiction: z.ZodOptional<z.ZodString>;
    recommendedAction: z.ZodString;
    targetInfoToRequest: z.ZodArray<z.ZodString, "many">;
    relatedTxHashes: z.ZodArray<z.ZodString, "many">;
    urgency: z.ZodEnum<["LOW", "MEDIUM", "HIGH", "CRITICAL"]>;
}, "strip", z.ZodTypeAny, {
    address: string;
    entityName: string;
    entityType: string;
    recommendedAction: string;
    targetInfoToRequest: string[];
    relatedTxHashes: string[];
    urgency: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
    jurisdiction?: string | undefined;
}, {
    address: string;
    entityName: string;
    entityType: string;
    recommendedAction: string;
    targetInfoToRequest: string[];
    relatedTxHashes: string[];
    urgency: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
    jurisdiction?: string | undefined;
}>;
export type SubpoenaRecommendation = z.infer<typeof SubpoenaRecommendationSchema>;
export declare const InvestigationReportSchema: z.ZodObject<{
    id: z.ZodString;
    investigationId: z.ZodString;
    title: z.ZodString;
    caseNumber: z.ZodString;
    target: z.ZodString;
    chain: z.ZodString;
    generatedAt: z.ZodDate;
    investigatorName: z.ZodString;
    executiveSummary: z.ZodString;
    observedFacts: z.ZodArray<z.ZodString, "many">;
    inferences: z.ZodArray<z.ZodString, "many">;
    attributions: z.ZodArray<z.ZodObject<{
        address: z.ZodString;
        entityId: z.ZodOptional<z.ZodString>;
        entityName: z.ZodOptional<z.ZodString>;
        entityType: z.ZodOptional<z.ZodEnum<["EXCHANGE", "MIXER", "BRIDGE", "MARKETPLACE", "GAMBLING", "SCAM", "KNOWN_ILLICIT", "SERVICE", "UNKNOWN"]>>;
        attributionType: z.ZodEnum<["OBSERVED", "INFERENCE", "ATTRIBUTION"]>;
        confidence: z.ZodNumber;
        explanation: z.ZodString;
        supportingEvidenceIds: z.ZodArray<z.ZodString, "many">;
    }, "strip", z.ZodTypeAny, {
        address: string;
        confidence: number;
        attributionType: "OBSERVED" | "INFERENCE" | "ATTRIBUTION";
        explanation: string;
        supportingEvidenceIds: string[];
        entityId?: string | undefined;
        entityName?: string | undefined;
        entityType?: "EXCHANGE" | "MIXER" | "BRIDGE" | "MARKETPLACE" | "GAMBLING" | "SCAM" | "KNOWN_ILLICIT" | "SERVICE" | "UNKNOWN" | undefined;
    }, {
        address: string;
        confidence: number;
        attributionType: "OBSERVED" | "INFERENCE" | "ATTRIBUTION";
        explanation: string;
        supportingEvidenceIds: string[];
        entityId?: string | undefined;
        entityName?: string | undefined;
        entityType?: "EXCHANGE" | "MIXER" | "BRIDGE" | "MARKETPLACE" | "GAMBLING" | "SCAM" | "KNOWN_ILLICIT" | "SERVICE" | "UNKNOWN" | undefined;
    }>, "many">;
    riskAssessment: z.ZodObject<{
        target: z.ZodString;
        targetType: z.ZodEnum<["address", "transaction", "txHash", "cluster", "investigation"]>;
        overallScore: z.ZodNumber;
        riskLevel: z.ZodEnum<["LOW", "MEDIUM", "HIGH", "CRITICAL"]>;
        factors: z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            name: z.ZodString;
            category: z.ZodString;
            scoreDelta: z.ZodNumber;
            maxPossible: z.ZodNumber;
            description: z.ZodString;
            severity: z.ZodEnum<["LOW", "MEDIUM", "HIGH", "CRITICAL"]>;
            evidenceIds: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
            evidenceChain: z.ZodDefault<z.ZodArray<z.ZodObject<{
                evidenceId: z.ZodString;
                ruleId: z.ZodString;
                patternType: z.ZodString;
                explanation: z.ZodString;
                transactionHashes: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
                wallets: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
                entityName: z.ZodOptional<z.ZodString>;
                entityType: z.ZodOptional<z.ZodString>;
                timestamp: z.ZodDate;
                severity: z.ZodString;
                confidence: z.ZodNumber;
            }, "strip", z.ZodTypeAny, {
                timestamp: Date;
                confidence: number;
                explanation: string;
                severity: string;
                transactionHashes: string[];
                ruleId: string;
                patternType: string;
                evidenceId: string;
                wallets: string[];
                entityName?: string | undefined;
                entityType?: string | undefined;
            }, {
                timestamp: Date;
                confidence: number;
                explanation: string;
                severity: string;
                ruleId: string;
                patternType: string;
                evidenceId: string;
                entityName?: string | undefined;
                entityType?: string | undefined;
                transactionHashes?: string[] | undefined;
                wallets?: string[] | undefined;
            }>, "many">>;
        }, "strip", z.ZodTypeAny, {
            id: string;
            name: string;
            category: string;
            description: string;
            severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            scoreDelta: number;
            maxPossible: number;
            evidenceIds: string[];
            evidenceChain: {
                timestamp: Date;
                confidence: number;
                explanation: string;
                severity: string;
                transactionHashes: string[];
                ruleId: string;
                patternType: string;
                evidenceId: string;
                wallets: string[];
                entityName?: string | undefined;
                entityType?: string | undefined;
            }[];
        }, {
            id: string;
            name: string;
            category: string;
            description: string;
            severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            scoreDelta: number;
            maxPossible: number;
            evidenceIds?: string[] | undefined;
            evidenceChain?: {
                timestamp: Date;
                confidence: number;
                explanation: string;
                severity: string;
                ruleId: string;
                patternType: string;
                evidenceId: string;
                entityName?: string | undefined;
                entityType?: string | undefined;
                transactionHashes?: string[] | undefined;
                wallets?: string[] | undefined;
            }[] | undefined;
        }>, "many">;
        evidenceList: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        summary: z.ZodString;
        calculatedAt: z.ZodDate;
        recommendations: z.ZodArray<z.ZodString, "many">;
        confidence: z.ZodOptional<z.ZodObject<{
            confidenceScore: z.ZodNumber;
            confidenceLevel: z.ZodEnum<["LOW", "MEDIUM", "HIGH", "VERIFIED"]>;
            strengths: z.ZodArray<z.ZodString, "many">;
            limitations: z.ZodArray<z.ZodString, "many">;
        }, "strip", z.ZodTypeAny, {
            confidenceScore: number;
            confidenceLevel: "LOW" | "MEDIUM" | "HIGH" | "VERIFIED";
            strengths: string[];
            limitations: string[];
        }, {
            confidenceScore: number;
            confidenceLevel: "LOW" | "MEDIUM" | "HIGH" | "VERIFIED";
            strengths: string[];
            limitations: string[];
        }>>;
    }, "strip", z.ZodTypeAny, {
        target: string;
        targetType: "txHash" | "address" | "cluster" | "transaction" | "investigation";
        overallScore: number;
        riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        factors: {
            id: string;
            name: string;
            category: string;
            description: string;
            severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            scoreDelta: number;
            maxPossible: number;
            evidenceIds: string[];
            evidenceChain: {
                timestamp: Date;
                confidence: number;
                explanation: string;
                severity: string;
                transactionHashes: string[];
                ruleId: string;
                patternType: string;
                evidenceId: string;
                wallets: string[];
                entityName?: string | undefined;
                entityType?: string | undefined;
            }[];
        }[];
        evidenceList: string[];
        summary: string;
        calculatedAt: Date;
        recommendations: string[];
        confidence?: {
            confidenceScore: number;
            confidenceLevel: "LOW" | "MEDIUM" | "HIGH" | "VERIFIED";
            strengths: string[];
            limitations: string[];
        } | undefined;
    }, {
        target: string;
        targetType: "txHash" | "address" | "cluster" | "transaction" | "investigation";
        overallScore: number;
        riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        factors: {
            id: string;
            name: string;
            category: string;
            description: string;
            severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            scoreDelta: number;
            maxPossible: number;
            evidenceIds?: string[] | undefined;
            evidenceChain?: {
                timestamp: Date;
                confidence: number;
                explanation: string;
                severity: string;
                ruleId: string;
                patternType: string;
                evidenceId: string;
                entityName?: string | undefined;
                entityType?: string | undefined;
                transactionHashes?: string[] | undefined;
                wallets?: string[] | undefined;
            }[] | undefined;
        }[];
        summary: string;
        calculatedAt: Date;
        recommendations: string[];
        confidence?: {
            confidenceScore: number;
            confidenceLevel: "LOW" | "MEDIUM" | "HIGH" | "VERIFIED";
            strengths: string[];
            limitations: string[];
        } | undefined;
        evidenceList?: string[] | undefined;
    }>;
    patterns: z.ZodArray<z.ZodObject<{
        ruleId: z.ZodString;
        patternType: z.ZodEnum<["FAN_OUT", "FAN_IN", "RAPID_MOVEMENT", "PEEL_CHAIN", "HIGH_HOP_MOVEMENT", "MIXER_INTERACTION", "BRIDGE_INTERACTION", "ILLICIT_INTERACTION", "CIRCULAR_FLOW", "STRUCTURING"]>;
        title: z.ZodString;
        description: z.ZodString;
        severity: z.ZodNumber;
        confidence: z.ZodNumber;
        evidence: z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            type: z.ZodString;
            title: z.ZodString;
            description: z.ZodString;
            confidence: z.ZodNumber;
            severity: z.ZodEnum<["LOW", "MEDIUM", "HIGH", "CRITICAL"]>;
            source: z.ZodOptional<z.ZodString>;
            timestamp: z.ZodDate;
            transactionHashes: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
            addresses: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
            metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        }, "strip", z.ZodTypeAny, {
            type: string;
            id: string;
            timestamp: Date;
            confidence: number;
            description: string;
            addresses: string[];
            title: string;
            severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            transactionHashes: string[];
            metadata?: Record<string, unknown> | undefined;
            source?: string | undefined;
        }, {
            type: string;
            id: string;
            timestamp: Date;
            confidence: number;
            description: string;
            title: string;
            severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            metadata?: Record<string, unknown> | undefined;
            source?: string | undefined;
            addresses?: string[] | undefined;
            transactionHashes?: string[] | undefined;
        }>, "many">;
        affectedAddresses: z.ZodArray<z.ZodString, "many">;
        affectedTxHashes: z.ZodArray<z.ZodString, "many">;
        metrics: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    }, "strip", z.ZodTypeAny, {
        confidence: number;
        description: string;
        title: string;
        severity: number;
        ruleId: string;
        patternType: "FAN_OUT" | "FAN_IN" | "RAPID_MOVEMENT" | "PEEL_CHAIN" | "HIGH_HOP_MOVEMENT" | "MIXER_INTERACTION" | "BRIDGE_INTERACTION" | "ILLICIT_INTERACTION" | "CIRCULAR_FLOW" | "STRUCTURING";
        evidence: {
            type: string;
            id: string;
            timestamp: Date;
            confidence: number;
            description: string;
            addresses: string[];
            title: string;
            severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            transactionHashes: string[];
            metadata?: Record<string, unknown> | undefined;
            source?: string | undefined;
        }[];
        affectedAddresses: string[];
        affectedTxHashes: string[];
        metrics?: Record<string, unknown> | undefined;
    }, {
        confidence: number;
        description: string;
        title: string;
        severity: number;
        ruleId: string;
        patternType: "FAN_OUT" | "FAN_IN" | "RAPID_MOVEMENT" | "PEEL_CHAIN" | "HIGH_HOP_MOVEMENT" | "MIXER_INTERACTION" | "BRIDGE_INTERACTION" | "ILLICIT_INTERACTION" | "CIRCULAR_FLOW" | "STRUCTURING";
        evidence: {
            type: string;
            id: string;
            timestamp: Date;
            confidence: number;
            description: string;
            title: string;
            severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            metadata?: Record<string, unknown> | undefined;
            source?: string | undefined;
            addresses?: string[] | undefined;
            transactionHashes?: string[] | undefined;
        }[];
        affectedAddresses: string[];
        affectedTxHashes: string[];
        metrics?: Record<string, unknown> | undefined;
    }>, "many">;
    evidenceLedger: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        type: z.ZodString;
        title: z.ZodString;
        description: z.ZodString;
        confidence: z.ZodNumber;
        severity: z.ZodEnum<["LOW", "MEDIUM", "HIGH", "CRITICAL"]>;
        source: z.ZodOptional<z.ZodString>;
        timestamp: z.ZodDate;
        transactionHashes: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        addresses: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    }, "strip", z.ZodTypeAny, {
        type: string;
        id: string;
        timestamp: Date;
        confidence: number;
        description: string;
        addresses: string[];
        title: string;
        severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        transactionHashes: string[];
        metadata?: Record<string, unknown> | undefined;
        source?: string | undefined;
    }, {
        type: string;
        id: string;
        timestamp: Date;
        confidence: number;
        description: string;
        title: string;
        severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        metadata?: Record<string, unknown> | undefined;
        source?: string | undefined;
        addresses?: string[] | undefined;
        transactionHashes?: string[] | undefined;
    }>, "many">;
    flowPaths: z.ZodArray<z.ZodObject<{
        source: z.ZodString;
        destination: z.ZodString;
        hops: z.ZodNumber;
        volume: z.ZodString;
        asset: z.ZodString;
        entitiesReached: z.ZodArray<z.ZodString, "many">;
    }, "strip", z.ZodTypeAny, {
        asset: string;
        source: string;
        destination: string;
        hops: number;
        volume: string;
        entitiesReached: string[];
    }, {
        asset: string;
        source: string;
        destination: string;
        hops: number;
        volume: string;
        entitiesReached: string[];
    }>, "many">;
    subpoenaRecommendations: z.ZodArray<z.ZodObject<{
        entityName: z.ZodString;
        entityType: z.ZodString;
        address: z.ZodString;
        jurisdiction: z.ZodOptional<z.ZodString>;
        recommendedAction: z.ZodString;
        targetInfoToRequest: z.ZodArray<z.ZodString, "many">;
        relatedTxHashes: z.ZodArray<z.ZodString, "many">;
        urgency: z.ZodEnum<["LOW", "MEDIUM", "HIGH", "CRITICAL"]>;
    }, "strip", z.ZodTypeAny, {
        address: string;
        entityName: string;
        entityType: string;
        recommendedAction: string;
        targetInfoToRequest: string[];
        relatedTxHashes: string[];
        urgency: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        jurisdiction?: string | undefined;
    }, {
        address: string;
        entityName: string;
        entityType: string;
        recommendedAction: string;
        targetInfoToRequest: string[];
        relatedTxHashes: string[];
        urgency: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        jurisdiction?: string | undefined;
    }>, "many">;
}, "strip", z.ZodTypeAny, {
    id: string;
    chain: string;
    target: string;
    title: string;
    caseNumber: string;
    investigatorName: string;
    patterns: {
        confidence: number;
        description: string;
        title: string;
        severity: number;
        ruleId: string;
        patternType: "FAN_OUT" | "FAN_IN" | "RAPID_MOVEMENT" | "PEEL_CHAIN" | "HIGH_HOP_MOVEMENT" | "MIXER_INTERACTION" | "BRIDGE_INTERACTION" | "ILLICIT_INTERACTION" | "CIRCULAR_FLOW" | "STRUCTURING";
        evidence: {
            type: string;
            id: string;
            timestamp: Date;
            confidence: number;
            description: string;
            addresses: string[];
            title: string;
            severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            transactionHashes: string[];
            metadata?: Record<string, unknown> | undefined;
            source?: string | undefined;
        }[];
        affectedAddresses: string[];
        affectedTxHashes: string[];
        metrics?: Record<string, unknown> | undefined;
    }[];
    attributions: {
        address: string;
        confidence: number;
        attributionType: "OBSERVED" | "INFERENCE" | "ATTRIBUTION";
        explanation: string;
        supportingEvidenceIds: string[];
        entityId?: string | undefined;
        entityName?: string | undefined;
        entityType?: "EXCHANGE" | "MIXER" | "BRIDGE" | "MARKETPLACE" | "GAMBLING" | "SCAM" | "KNOWN_ILLICIT" | "SERVICE" | "UNKNOWN" | undefined;
    }[];
    investigationId: string;
    generatedAt: Date;
    executiveSummary: string;
    observedFacts: string[];
    inferences: string[];
    riskAssessment: {
        target: string;
        targetType: "txHash" | "address" | "cluster" | "transaction" | "investigation";
        overallScore: number;
        riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        factors: {
            id: string;
            name: string;
            category: string;
            description: string;
            severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            scoreDelta: number;
            maxPossible: number;
            evidenceIds: string[];
            evidenceChain: {
                timestamp: Date;
                confidence: number;
                explanation: string;
                severity: string;
                transactionHashes: string[];
                ruleId: string;
                patternType: string;
                evidenceId: string;
                wallets: string[];
                entityName?: string | undefined;
                entityType?: string | undefined;
            }[];
        }[];
        evidenceList: string[];
        summary: string;
        calculatedAt: Date;
        recommendations: string[];
        confidence?: {
            confidenceScore: number;
            confidenceLevel: "LOW" | "MEDIUM" | "HIGH" | "VERIFIED";
            strengths: string[];
            limitations: string[];
        } | undefined;
    };
    evidenceLedger: {
        type: string;
        id: string;
        timestamp: Date;
        confidence: number;
        description: string;
        addresses: string[];
        title: string;
        severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        transactionHashes: string[];
        metadata?: Record<string, unknown> | undefined;
        source?: string | undefined;
    }[];
    flowPaths: {
        asset: string;
        source: string;
        destination: string;
        hops: number;
        volume: string;
        entitiesReached: string[];
    }[];
    subpoenaRecommendations: {
        address: string;
        entityName: string;
        entityType: string;
        recommendedAction: string;
        targetInfoToRequest: string[];
        relatedTxHashes: string[];
        urgency: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        jurisdiction?: string | undefined;
    }[];
}, {
    id: string;
    chain: string;
    target: string;
    title: string;
    caseNumber: string;
    investigatorName: string;
    patterns: {
        confidence: number;
        description: string;
        title: string;
        severity: number;
        ruleId: string;
        patternType: "FAN_OUT" | "FAN_IN" | "RAPID_MOVEMENT" | "PEEL_CHAIN" | "HIGH_HOP_MOVEMENT" | "MIXER_INTERACTION" | "BRIDGE_INTERACTION" | "ILLICIT_INTERACTION" | "CIRCULAR_FLOW" | "STRUCTURING";
        evidence: {
            type: string;
            id: string;
            timestamp: Date;
            confidence: number;
            description: string;
            title: string;
            severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            metadata?: Record<string, unknown> | undefined;
            source?: string | undefined;
            addresses?: string[] | undefined;
            transactionHashes?: string[] | undefined;
        }[];
        affectedAddresses: string[];
        affectedTxHashes: string[];
        metrics?: Record<string, unknown> | undefined;
    }[];
    attributions: {
        address: string;
        confidence: number;
        attributionType: "OBSERVED" | "INFERENCE" | "ATTRIBUTION";
        explanation: string;
        supportingEvidenceIds: string[];
        entityId?: string | undefined;
        entityName?: string | undefined;
        entityType?: "EXCHANGE" | "MIXER" | "BRIDGE" | "MARKETPLACE" | "GAMBLING" | "SCAM" | "KNOWN_ILLICIT" | "SERVICE" | "UNKNOWN" | undefined;
    }[];
    investigationId: string;
    generatedAt: Date;
    executiveSummary: string;
    observedFacts: string[];
    inferences: string[];
    riskAssessment: {
        target: string;
        targetType: "txHash" | "address" | "cluster" | "transaction" | "investigation";
        overallScore: number;
        riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        factors: {
            id: string;
            name: string;
            category: string;
            description: string;
            severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            scoreDelta: number;
            maxPossible: number;
            evidenceIds?: string[] | undefined;
            evidenceChain?: {
                timestamp: Date;
                confidence: number;
                explanation: string;
                severity: string;
                ruleId: string;
                patternType: string;
                evidenceId: string;
                entityName?: string | undefined;
                entityType?: string | undefined;
                transactionHashes?: string[] | undefined;
                wallets?: string[] | undefined;
            }[] | undefined;
        }[];
        summary: string;
        calculatedAt: Date;
        recommendations: string[];
        confidence?: {
            confidenceScore: number;
            confidenceLevel: "LOW" | "MEDIUM" | "HIGH" | "VERIFIED";
            strengths: string[];
            limitations: string[];
        } | undefined;
        evidenceList?: string[] | undefined;
    };
    evidenceLedger: {
        type: string;
        id: string;
        timestamp: Date;
        confidence: number;
        description: string;
        title: string;
        severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        metadata?: Record<string, unknown> | undefined;
        source?: string | undefined;
        addresses?: string[] | undefined;
        transactionHashes?: string[] | undefined;
    }[];
    flowPaths: {
        asset: string;
        source: string;
        destination: string;
        hops: number;
        volume: string;
        entitiesReached: string[];
    }[];
    subpoenaRecommendations: {
        address: string;
        entityName: string;
        entityType: string;
        recommendedAction: string;
        targetInfoToRequest: string[];
        relatedTxHashes: string[];
        urgency: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        jurisdiction?: string | undefined;
    }[];
}>;
export type InvestigationReport = z.infer<typeof InvestigationReportSchema>;
//# sourceMappingURL=investigation.d.ts.map