import { z } from "zod";
export declare const TracePathOptionsSchema: z.ZodObject<{
    startAddress: z.ZodString;
    destinationAddress: z.ZodOptional<z.ZodString>;
    destinationEntityType: z.ZodOptional<z.ZodString>;
    maxHops: z.ZodDefault<z.ZodNumber>;
    minAmount: z.ZodOptional<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    maxHops: number;
    startAddress: string;
    destinationAddress?: string | undefined;
    destinationEntityType?: string | undefined;
    minAmount?: number | undefined;
}, {
    startAddress: string;
    destinationAddress?: string | undefined;
    maxHops?: number | undefined;
    destinationEntityType?: string | undefined;
    minAmount?: number | undefined;
}>;
export type TracePathOptions = z.infer<typeof TracePathOptionsSchema>;
export declare const TracePathDetailSchema: z.ZodObject<{
    id: z.ZodString;
    pathIndex: z.ZodNumber;
    nodes: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        address: z.ZodString;
        label: z.ZodString;
        type: z.ZodDefault<z.ZodEnum<["address", "entity", "contract", "cluster"]>>;
        chain: z.ZodString;
        entityId: z.ZodOptional<z.ZodString>;
        entityName: z.ZodOptional<z.ZodString>;
        entityType: z.ZodOptional<z.ZodString>;
        riskScore: z.ZodOptional<z.ZodNumber>;
        clusterId: z.ZodOptional<z.ZodString>;
        balance: z.ZodOptional<z.ZodString>;
        formattedBalance: z.ZodOptional<z.ZodString>;
        txCount: z.ZodOptional<z.ZodNumber>;
        firstSeen: z.ZodOptional<z.ZodDate>;
        lastSeen: z.ZodOptional<z.ZodDate>;
        tags: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
        isTarget: z.ZodOptional<z.ZodBoolean>;
        isSuspect: z.ZodOptional<z.ZodBoolean>;
        hopLevel: z.ZodOptional<z.ZodNumber>;
        metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    }, "strip", z.ZodTypeAny, {
        address: string;
        type: "address" | "entity" | "contract" | "cluster";
        id: string;
        chain: string;
        label: string;
        metadata?: Record<string, unknown> | undefined;
        entityId?: string | undefined;
        entityName?: string | undefined;
        entityType?: string | undefined;
        riskScore?: number | undefined;
        clusterId?: string | undefined;
        balance?: string | undefined;
        formattedBalance?: string | undefined;
        txCount?: number | undefined;
        firstSeen?: Date | undefined;
        lastSeen?: Date | undefined;
        tags?: string[] | undefined;
        isTarget?: boolean | undefined;
        isSuspect?: boolean | undefined;
        hopLevel?: number | undefined;
    }, {
        address: string;
        id: string;
        chain: string;
        label: string;
        type?: "address" | "entity" | "contract" | "cluster" | undefined;
        metadata?: Record<string, unknown> | undefined;
        entityId?: string | undefined;
        entityName?: string | undefined;
        entityType?: string | undefined;
        riskScore?: number | undefined;
        clusterId?: string | undefined;
        balance?: string | undefined;
        formattedBalance?: string | undefined;
        txCount?: number | undefined;
        firstSeen?: Date | undefined;
        lastSeen?: Date | undefined;
        tags?: string[] | undefined;
        isTarget?: boolean | undefined;
        isSuspect?: boolean | undefined;
        hopLevel?: number | undefined;
    }>, "many">;
    edges: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        source: z.ZodString;
        target: z.ZodString;
        txHash: z.ZodString;
        asset: z.ZodString;
        amount: z.ZodString;
        formattedAmount: z.ZodString;
        valueUsd: z.ZodOptional<z.ZodNumber>;
        timestamp: z.ZodDate;
        chain: z.ZodString;
        fee: z.ZodOptional<z.ZodString>;
        isTokenTransfer: z.ZodOptional<z.ZodBoolean>;
        tokenSymbol: z.ZodOptional<z.ZodString>;
        isContractCall: z.ZodOptional<z.ZodBoolean>;
        confidence: z.ZodDefault<z.ZodNumber>;
        isCrossChain: z.ZodOptional<z.ZodBoolean>;
        bridgeName: z.ZodOptional<z.ZodString>;
        metadata: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    }, "strip", z.ZodTypeAny, {
        txHash: string;
        amount: string;
        formattedAmount: string;
        id: string;
        chain: string;
        timestamp: Date;
        asset: string;
        source: string;
        target: string;
        confidence: number;
        tokenSymbol?: string | undefined;
        fee?: string | undefined;
        isContractCall?: boolean | undefined;
        metadata?: Record<string, unknown> | undefined;
        valueUsd?: number | undefined;
        isTokenTransfer?: boolean | undefined;
        isCrossChain?: boolean | undefined;
        bridgeName?: string | undefined;
    }, {
        txHash: string;
        amount: string;
        formattedAmount: string;
        id: string;
        chain: string;
        timestamp: Date;
        asset: string;
        source: string;
        target: string;
        tokenSymbol?: string | undefined;
        fee?: string | undefined;
        isContractCall?: boolean | undefined;
        metadata?: Record<string, unknown> | undefined;
        valueUsd?: number | undefined;
        isTokenTransfer?: boolean | undefined;
        confidence?: number | undefined;
        isCrossChain?: boolean | undefined;
        bridgeName?: string | undefined;
    }>, "many">;
    hopCount: z.ZodNumber;
    totalVolume: z.ZodNumber;
    asset: z.ZodString;
    timeSpanSeconds: z.ZodNumber;
    knownEntities: z.ZodArray<z.ZodString, "many">;
    suspiciousIndicators: z.ZodArray<z.ZodString, "many">;
}, "strip", z.ZodTypeAny, {
    id: string;
    asset: string;
    nodes: {
        address: string;
        type: "address" | "entity" | "contract" | "cluster";
        id: string;
        chain: string;
        label: string;
        metadata?: Record<string, unknown> | undefined;
        entityId?: string | undefined;
        entityName?: string | undefined;
        entityType?: string | undefined;
        riskScore?: number | undefined;
        clusterId?: string | undefined;
        balance?: string | undefined;
        formattedBalance?: string | undefined;
        txCount?: number | undefined;
        firstSeen?: Date | undefined;
        lastSeen?: Date | undefined;
        tags?: string[] | undefined;
        isTarget?: boolean | undefined;
        isSuspect?: boolean | undefined;
        hopLevel?: number | undefined;
    }[];
    edges: {
        txHash: string;
        amount: string;
        formattedAmount: string;
        id: string;
        chain: string;
        timestamp: Date;
        asset: string;
        source: string;
        target: string;
        confidence: number;
        tokenSymbol?: string | undefined;
        fee?: string | undefined;
        isContractCall?: boolean | undefined;
        metadata?: Record<string, unknown> | undefined;
        valueUsd?: number | undefined;
        isTokenTransfer?: boolean | undefined;
        isCrossChain?: boolean | undefined;
        bridgeName?: string | undefined;
    }[];
    totalVolume: number;
    pathIndex: number;
    hopCount: number;
    timeSpanSeconds: number;
    knownEntities: string[];
    suspiciousIndicators: string[];
}, {
    id: string;
    asset: string;
    nodes: {
        address: string;
        id: string;
        chain: string;
        label: string;
        type?: "address" | "entity" | "contract" | "cluster" | undefined;
        metadata?: Record<string, unknown> | undefined;
        entityId?: string | undefined;
        entityName?: string | undefined;
        entityType?: string | undefined;
        riskScore?: number | undefined;
        clusterId?: string | undefined;
        balance?: string | undefined;
        formattedBalance?: string | undefined;
        txCount?: number | undefined;
        firstSeen?: Date | undefined;
        lastSeen?: Date | undefined;
        tags?: string[] | undefined;
        isTarget?: boolean | undefined;
        isSuspect?: boolean | undefined;
        hopLevel?: number | undefined;
    }[];
    edges: {
        txHash: string;
        amount: string;
        formattedAmount: string;
        id: string;
        chain: string;
        timestamp: Date;
        asset: string;
        source: string;
        target: string;
        tokenSymbol?: string | undefined;
        fee?: string | undefined;
        isContractCall?: boolean | undefined;
        metadata?: Record<string, unknown> | undefined;
        valueUsd?: number | undefined;
        isTokenTransfer?: boolean | undefined;
        confidence?: number | undefined;
        isCrossChain?: boolean | undefined;
        bridgeName?: string | undefined;
    }[];
    totalVolume: number;
    pathIndex: number;
    hopCount: number;
    timeSpanSeconds: number;
    knownEntities: string[];
    suspiciousIndicators: string[];
}>;
export type TracePathDetail = z.infer<typeof TracePathDetailSchema>;
//# sourceMappingURL=trace.d.ts.map